### ISSUE TITLE
dials.image_viewer: colour choices for masked pixels

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1038]
In default greyscale view image looks sensible:

![Screenshot 2019-11-25 at 07 48 48](https://user-images.githubusercontent.com/1241716/69521937-0e51c500-0f58-11ea-88db-af270b8c5ee1.png)

Invert and it looks impossible to interpret as the masked pixels are still yellow

![Screenshot 2019-11-25 at 07 49 32](https://user-images.githubusercontent.com/1241716/69521976-23c6ef00-0f58-11ea-9e28-2bec8dba079b.png)

Suggest adaptive colour choice for the mask pixels and a user toggle to either have them masked to background or contrasting.

**Comment by dagewa** [comment]
What data set is this, that the module gaps are marked as "saturated" (yellow) rather than "masked" (red)?

**Comment by dagewa** [comment]
Anyway, the yellowness is set here for both `COLOR_GRAY` and `COLOR_INVERT`
https://github.com/cctbx/cctbx_project/blob/966e457f62a5e2b81545efca6dd8cff1b2e50e99/iotbx/detectors/display.h#L486-L489
R,G,B = 254,254,1

**Comment by dagewa** [comment]
![Screenshot from 2019-12-07 11-05-52](https://user-images.githubusercontent.com/11502083/70373634-9c776500-18e1-11ea-95b0-ab198161e20b.png)
I wasn't able to reproduce this using a recent Eiger dataset from I04. The masked pixels have a red, rather than yellow, overlay. The values of masked pixels are all set to 65535 (either module gaps or masked bad pixels), which is a surprise to me.
