### ISSUE TITLE
Non-obvious error message - dials.integrate with no reflections

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1060]
`dials.integrate refined.expt` gets as far as predicting reflections and then crashes with
```
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Not enough information to set profile parameters
```
This is surely true, but the user could have been told much earlier and with a more specific error message (like "have you forgotten refined.refl?")

**Comment by rjgildea** [comment]
I think the issue here is that input reflections don't have to be provided, but if they are not, then the profile model parameters need to be provided on the command line:

https://github.com/dials/dials/blob/9995b3d0a8d09108c974c3386e018f8c3dfbe00e/command_line/integrate.py#L325-L337

The actual error that is raised could be more informative:
https://github.com/dials/dials/blob/9995b3d0a8d09108c974c3386e018f8c3dfbe00e/algorithms/profile_model/gaussian_rs/model.py#L271-L272

**Comment by dagewa** [comment]
Yes, possibly it isn't worth checking all of that up front, so maybe just the error message needs improvement.
