### ISSUE TITLE
In indexing, is it an error to find no lattices?

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1080]
Question raised in https://github.com/dials/dials/commit/56dc83221c08b5ef33153469d82c8d89732e432b - if we find no lattices is that an error?

Context: 
- if in spot finding we find no spots, we report that no spots were found. 
- if we say `max_lattices=5` and we find 4 this is fine
- the fix above _mostly_ works around insufficient input validation

Is it correct that failure to index returns a non-zero result? Discuss.

**Comment by ndevenish** [comment]
I mean it's semantics really; but I'd argue given the entire point of running dials.index is to extract a lattice, not finding a lattice is an error. Put another way, given input files `{x}` we want it to produce output files. With no lattice, there is no output file.

If anything, I'd argue a completely null result from spotfinding should maybe an error, though obviously it's more of a continuous result rather than a discrete one.

**Comment by graeme-winter** [comment]
@ndevenish valid - however with https://github.com/dials/dials/issues/1029 in mind there _would be_ an output file, but it would be the same as the input. I was trying to work out consistency here re: indexing stills - which gets very close to the spot finding use case...

**Comment by ndevenish** [comment]
I mean I guess one argument could be that you want to distinguish between failure-to-index and failed-to-run, to retry with a different approach in e.g. some automated pipeline. That could be exit code... In case where no indexing result the output file should be exactly the same as the input file, right? Is that not confusing? Doesn't that look like it worked?
