### ISSUE TITLE
mac builds broken due to #1077

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#1098]
From an empty directory and on MacOS only:
```bash
curl https://raw.githubusercontent.com/dials/dials/master/installer/bootstrap.py > bootstrap.py
python bootstrap.py
. build/setpaths.sh
cd modules/dials
pytest --regression  algorithms/indexing/test_index.py::test_index_small_molecule_multi_sequence_4
```
=>
```
  File "modules/dials/algorithms/indexing/indexer.py", line 349, in __init__
    self.reflections = self.reflections.select(strong_sel)
RuntimeError: boost::bad_get: failed value get using boost::get
```

bisected it to commit 063a5db7fee383178b8c05a827d9f9a5cbc11552

**Comment by rjgildea** [comment]
I can confirm it fails my (Python 2.7) mac build.

**Comment by rjgildea** [comment]
Confirmed test failure goes away after updating dials_regression. Cause of error due to `"id"` column in input reflection files being of type `flex.size_t` (where it is now assumed to be `flex.int`), failing at this line:
https://github.com/dials/dials/blob/c7679608d75fa43b8b4b1571141ed4550ee588df/array_family/boost_python/flex_table_suite.h#L644
and ultimately here:
https://github.com/dials/dials/blob/master/array_family/flex_table.h#L138

**Comment by Anthchirp** [comment]
Good detective work. The mac mini has a static copy of d_r that is no longer updated. I can do a manual update, but the best fix there is to stop using d_r.

**Comment by Anthchirp** [comment]
Confirmed fixed
