### ISSUE TITLE
dials.spot_counts_per_image broken

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1103]
... probably side-effect of recent changes with no tests - 

 - write test
 - fix code

Error manifests as
```
cs03r-sc-serv-16 work0 :) $ dials.spot_counts_per_image imported.expt strong.refl | tee scpi.log
Unknown experiments in reflection list
```

**Comment by rjgildea** [comment]
It _is_ tested, however this highlights a drawback of only testing that specific part, i.e. upstream import/spotfinding output has changed, but this isn't reflected in this test because it is using input files that pre-date these changes:
https://github.com/dials/dials/blob/master/test/command_line/test_spot_counts_per_image.py

**Comment by graeme-winter** [comment]
The tool is fixed (thank you @rjgildea ) however 

```
Results (715.57s):
    1022 passed
       1 failed
         - test/command_line/test_spotfinder.py:301 test_find_spots_with_per_image_statistics
      17 skipped
```

Ah, fixed by @Anthchirp  in https://github.com/dials/dials/compare/f32e402affe7...8631c9b6f5cc
