### ISSUE TITLE
dials.combine_experiments broken for subset output

### ISSUE THREAD

**Issue by jbeilstenedmands** [dials/dials#1120]
Recent experiment identifier changes have broken combine_experiments for options such as `n_subset=`

Add tests for these options and fix.

**Comment by biochem-fan** [comment]
I am afraid this is still broken. The program runs but the output is corrupted.

Please look at my test case from SACLA (MPCCD), which contains 4 lysozyme stills shots.
https://drive.google.com/open?id=1jIFxaFmfnBaPJBd-hgG2eZqSCWuty-a9
Feel free to copy this to `dials-test` if useful; I will delete the above file when this issue is closed.

# To reproduce

```
dials.combine_experiments reference_from_experiment.average_detector=True reference_from_experiment.average_hierarchy_level=0 output.experiments_filename=test_combined.expt output.reflections_filename=test_combined.refl combine.phil n_subset=3 n_subset_method=random
```
followed by `dials.refine test_combined.expt test_combined.refl` fails saying:
```
...
  File "/prog/dials/modules/dials/algorithms/refinement/parameterisation/model_parameters.py", line 259, in set_param_vals
    self.compose()
  File "/prog/dials/modules/dials/algorithms/refinement/parameterisation/crystal_parameters.py", line 204, in compose
    newB, self._dstate_dp = self._compose_core([p.value for p in self._param])
  File "/prog/dials/modules/dials/algorithms/refinement/parameterisation/crystal_parameters.py", line 144, in _compose_core
    "Unable to compose the crystal model. Please check that the "
RuntimeError: Please report this error to dials-support@lists.sourceforge.net: Unable to compose the crystal model. Please check that the experiments match the indexing of the reflections.
```

If this succeeds, please try again. Because of stochasticity in `n_subset`, this sometimes succeeds.

# Successful cases

Without `n_subset`, it always works.

I also created `combine_omitN.phil` (N=0,1,2,3), omitting each one of the four inputs, to see if one of the input is broken. All of them works fine.

So the problem is in `n_subset` itself.

**Comment by jbeilstenedmands** [comment]
Thanks @biochem-fan  for reporting this and providing the example data. Basically the ordering of the output (subset) experiment list was different to the input, while the reflection table ordering was unchanged, leading to the issue in dials.refine. 
I was then able to test for this by modifying the existing test, so didn't feel the need to write an additional test using your data. Please reopen if you encounter another similar issue.
