### ISSUE TITLE
Is trusted_range useful in mask generation?

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1139]
Continuing from work here:
_Originally posted by @graeme-winter in https://github.com/dials/dials/pull/1084#issuecomment-574100289_

Currently the trusted_range is ignored by default during mask creation, which is fast, but can lead to hot pixels affecting found spots. Is this really a problem? We need datasets to explore whether the presence of hot pixels has a significant negative effect.

**Comment by graeme-winter** [comment]
Also whether the presence of hot pixels can be determined from the output reflection list.

**Comment by graeme-winter** [comment]
Convenient overloaded data set from i03

https://ispyb.diamond.ac.uk/dc/visit/cm23003-5/id/4366767

**Comment by graeme-winter** [comment]
Right, turns out this is actively unuseful in the mask generation since it is _applied anyways_ 

https://github.com/xia2/xia2/issues/231#issuecomment-586884464

All this option does in spot finding is take a very long time to make a useless mask... 

Conclusions: no it is not useful. It should be eliminated I humbly suggest.
