### ISSUE TITLE
Live spot finding view in dials.image_viewer

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#1200]
The dials image viewer is very useful for adjusting spot finding parameters - it would be _even more useful_ if one could view the image and the pixels which are identified as "spot" at the same time i.e. something like

![Screenshot 2020-03-20 at 10 01 27](https://user-images.githubusercontent.com/1241716/77153628-0206f000-6a92-11ea-9a53-6de72968e0b9.png)

computed real-time...

**Comment by dagewa** [comment]
Would using the threshold image as a mask to determine where to put green boxes be good enough, or you want to run actual spot finding through image viewer?

**Comment by graeme-winter** [comment]
@dagewa what you suggest is precisely what I had in mind - in image view, if "highlight threshold pixels" or something switched on also show little green boxen.

**Comment by dagewa** [comment]
I've done some work in this part of the code, so I'll pick this up.

**Comment by graeme-winter** [comment]
👍  thank you

**Comment by rjgildea** [comment]
Of course not all thresholded pixels make it through to become part of actual "spots", because of all the post-thresholding spot-finding filtering steps, etc. But if a pixel isn't in the threshold map to begin with, then it _definitely_ won't be part of a spot. If you wanted to run actual spot-finding code, I guess you could define a window around the current image to run spot-finding on, and display those results as an approximation?

**Comment by dagewa** [comment]
Perhaps we can have both. A mark up display of threshold pixels (fast), plus the ability to run `dials.find_spots` directly from the image viewer (slow). Then we get to see the threshold pixels that don't make it into actual spots

**Comment by graeme-winter** [comment]
That would mean you have to be able to show e.g. max_sep parameters etc. tho - possibly annoying / cumbersome?

**Comment by dagewa** [comment]
I would start with the first part (show threshold as overlay) and we can think about running `find_spots` from the image viewer separately, later on.
