### ISSUE TITLE
Anomalous signal being lost during processing

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1215]
This has come up a few times in the past, but I couldn't find a ticket specifically about it. I know @jbeilstenedmands has begun looking into it, but I don't think we're ready to assign to anybody yet as the problem is not well understood.

We should collate here a list of datasets that demonstrate the issue, where XDS gives a clear anomalous signal but DIALS does not.

The problem might not be limited to differences in scaling. It would be useful to compare `xds`, `dials.scale` and `aimless` with data integrated either with `dials.integrate` or `xds`. Signal may be lost already for some classes of reflections during integration, such as those near the rotation axis (#201), partials (#473) or low resolution reflections in general (#1187)

**Comment by dagewa** [comment]
Datasets to look at

1. /dls/i23/data/2020/nr23571-55/FutA/20200225/4p5kev/FutA_2/FutA_1_#####.cbf (@mevol) 
2. /dls/i03/data/2020/mx26568-3/Thermolysin/thermo_1/thermo_1_1_master.h5 (@mevol)

**Comment by dagewa** [comment]
More from @mevol, for which experimental phasing is successful after the xia2 3dii pipeline, but fails for the dials pipeline:

3. /dls/i03/data/2020/cm26458-1/20200305/thermo/line/thermo_1_2_master.h5
4. /dls/i03/data/2020/mx26568-3/Ferritin/ferr_1/ferr_1_1_master.h5
5. /dls/i03/data/2020/mx26568-3/Insulin/ins_1/ins_1_8_master.h5
6. /dls/i24/data/2020/mx23694-31/auto/TestLysozyme/Lys1/Lys1_1_####.cbf
7. /dls/i04/data/2020/mx26592-2/TestThermolysin/thremolysin_5/thremolysin_5_1_master.h5
8. /dls/i04/data/2020/mx26592-2/TestThermolysin/thermo10/thermo10_1_master.h5
9. /dls/i03/data/2020/cm26458-1/20200212/fstest/test_3_master.h5

**Comment by dagewa** [comment]
and for the latest run, a lot of thaumatin that builds after phasing from `3dii` data, but not from `dials`

10. /dls/i04/data/2020/cm26459-6/auto/TestThaumatin/thaumatin5/thaumatin5_6_master.h5
11. /dls/i04/data/2020/cm26459-6/auto/TestThaumatin/thaumatin6/thaumatin6_6_master.h5 
12. /dls/i04/data/2020/cm26459-6/auto/TestThaumatin/thaumatin5/thaumatin5_3_master.h5
13. /dls/i04/data/2020/cm26459-6/20200515/TestThaumatin/thaumatin1/thaumatin1_2_master.h5 
14. /dls/i04/data/2020/cm26459-2/20200506/TestThaumatin/thaumatin1/thaumatin1_1_master.h5 

plus an insulin dataset, which is given a low probability of success in phasing from `dials` data (5.6%) and an even lower probability of success from `3dii` data (3.9%) and yet the `3dii` → BigEP job succeeds, whilst the `dials` → BigEP job fails. 

15. /dls/i03/data/2020/cm26458-2/gw/screen_collect_test/insu_11/insu_11_2_master.h5

**Comment by dagewa** [comment]
This from @graeme-winter has also been used for investigation recently. I don't know the XDS vs DIALS characteristics here.

16. /dls/mx-scratch/gw56/anomalous-signal-smoking-gun/data

**Comment by jbeilstenedmands** [comment]
To help us get started investigating where the differences arise in the data, I've been developing a little plotter, currently available in dials_scratch.

Here is an insulin dataset I processed, possibly the one originally mentioned by Irakli.

![intensity_viewer](https://user-images.githubusercontent.com/30625594/85377130-899c4900-b530-11ea-8d8b-9d56920f04a8.png)

This was generated with the command
```
dials.python ~/dials/modules/dials_scratch/jbe/intensity_viewer.py xia2-dials/DataFiles/AUTOMATIC_DEFAULT_scaled.{expt,refl} xia2-3dii-I23/DataFiles/AUTOMATIC_DEFAULT_NATIVE_SWEEP1_CORRECT.HKL
```

As you can see, it can plot dials .expt,.refl files and xds_ascii data side by side (also MTZ files, not shown). Anomalous data is separated (triangles and circles). For example here, the anomalous separation for the XDS data is much more evident than in the DIALS data.

**Comment by rjgildea** [comment]
Looks good - although it might be clearer to see the differences if the +/- reflections are also plotted in different colours?

Can it also show the raw integrated intensities? It might be useful to see whether the differences were already there before scaling (and also if there's any difference between summation and profile fitting).

**Comment by jbeilstenedmands** [comment]
Okay, I've added the ability to also plot INTEGRATE.HKL files also:

Looking at the same reflection group as above, it looks like in this case, the integrated data from both pipelines looks very similar, however the XDS scaling seems to pull out an anomalous signal whereas the DIALS scaling does not.

![intensity_viewer_2](https://user-images.githubusercontent.com/30625594/85382790-37125b00-b537-11ea-8ce9-6c05a5f8a038.png)

**Comment by jbeilstenedmands** [comment]
I've had a look at the dataset 7 processing: /dls/i04/data/2020/mx26592-2/TestThermolysin/thremolysin_5/thremolysin_5_1_master.h5

It seems there isn't really an issue with the anomalous signal in this dataset.
![image](https://user-images.githubusercontent.com/30625594/86456693-6173cd80-bd1a-11ea-8413-74875beb0a08.png)
**For xia2-dials:**
`Big_ep_predict: {"success": 46.943, "failure": 53.057, "threshold": 80.0, "class": 0, "metrics": {"Low resolution limit": "68.57655", "Anomalous slope": "0.57965", "Anomalous correlation": "0.54321", "dI/s(dI)": "0.77333", "dF/F": "0.04942", "f\"": "0.76853"}}`
`Dials-dimple:
overall_r: 0.2005, free_r: 0.2149`

**For xia2-3dii**
`Big_ep_predict: {"success": 61.64, "failure": 38.36, "threshold": 80.0, "class": 0, "metrics": {"Low resolution limit": "68.58433", "Anomalous slope": "1.21106", "Anomalous correlation": "0.70257", "dI/s(dI)": "1.40870", "dF/F": "0.04511", "f\"": "0.76853"}}`
`3dii-dimple:
overall_r: 0.2055, free_r: 0.2215`
`3dii-big_ep:
R= 0.22   Rfree= 0.24, Residues built: 313    Side chains: 313, Model-map correlation: 0.82 , Resolution:  1.43`

So the results from dimple are actually slightly better for dials, and the only issue is that big_ep wasn't run for xia2-dials, possibly because d"/sig is below the threshold?

**Comment by jbeilstenedmands** [comment]
Summary of investigation into some of the other datasets. In the data processing folders, none of these have big EP automatically triggered on xia2-dials runs, presumably due to the thresholds, so can't use this to compare. Looking at dimple and anomalous merging stats instead.

- 8: thermo - dials and 3dii dimple results comparable, comparable cc_anom.

- 9: fstest - No dimple run for either xia2 job so not able to compare

- 10-14 thaum. In general dimple results consistently worse for dials by about 0.01-0.02 and not as good cc_anom, so worth further investigation. Manual triggering of big_ep on dataset no 10 gave better result for xia2-dials than xia2-3dii

- 15: ins. Dimple results notably worse for xia2-dials than xia2-3dii, but both not great and low anomalous signal in all data processing pipelines, so possibly not a good dataset for further investigation.

**Comment by dagewa** [comment]
Thanks James. I hadn't realised in some cases the "failures" were just due to BigEP not being triggered. It makes sense to filter the list to only include datasets that genuinely give better anomalous signal in XDS, so that phasing either works better for XDS, or the DIALS job fails to phase.

**Comment by mevol** [comment]
Just to be clear, for several of those data sets a manual run was triggered with no result. Also, since my first round of analysis Irakli has done some work on BigEP so I don't think one can compare the results from 4/5 months ago with a rerun now.

**Comment by jbeilstenedmands** [comment]
Following on from the changes to scaling error modelling, as well as other accumulated changes, I asked @isikhar to retrigger the autoprocessing to see if any improvement has been made. I will post a summary of the findings for each dataset for a selection of 5 datasets. Processed with a recent nightly build XIA2 0.7.80-g9f6881dd, DIALS 3.dev.149-g6a7d752e2.

**Ferritin Dataset** (number 4 above) https://ispyb.diamond.ac.uk/dc/visit/mx26568-3/id/4893639

![image](https://user-images.githubusercontent.com/30625594/89535683-a8a81f00-d7ee-11ea-9bac-fe83a1ef7299.png)

![image](https://user-images.githubusercontent.com/30625594/89536590-0c7f1780-d7f0-11ea-8cd1-3ab73d0bb701.png)

Summary
Merging statistics and anomalous statistics appear very similar for xia2-dials and xia2-3dii. Dimple results only ~0.01 better for xia2-3dii, however big_ep fails for xia2-dials and succeeds for xia2-3dii. For this dataset, this suggests that the issue is in data integration rather than loss of anomalous signal?

Details
- xia2-dials ep_predict. ```{ "success": 82.347, "failure": 17.653, "threshold": 80.0, "class": 1,'
"metrics": {
	"Low resolution limit": "90.73815",
	"Anomalous slope": "0.66147",
	"Anomalous correlation": "0.56603",
	"dI/s(dI)": "0.72192", 
	"dF/F": "0.12495", 
	"f\"": "3.85475”
}}```
- xia2-3dii ep_predict. ```{"success": 94.127, "failure": 5.873,
"threshold": 80.0, "class": 1, 
"metrics": {
	"Low resolution limit": "90.71075", 	"Anomalous slope": "0.50393", 	"Anomalous correlation": "0.56984", 	"dI/s(dI)": "0.54261",
	"dF/F": "0.10992",
	 "f\"": "3.85475”
}}```
- xia2-dials big_ep ```Overall best on cycle 7   R= 0.49   Rfree= 0.53
Residues built: 103 Side chains: 8
Model-map correlation: 0.49  
Resolution:  2.27```
- xia2-3dii big_ep ```Overall best on cycle 6   R= 0.28   Rfree= 0.32
Residues built: 161 Side chains: 150
Model-map correlation: 0.78  
Resolution:  2.47```
- xia2-dials dimple ```overall_r: 0.2132
free_r: 0.2847```
- xia2-3dii dimple ```overall_r: 0.2054
free_r: 0.2708```

**Comment by jbeilstenedmands** [comment]
**Thermolysin Dataset** (number 2 above) https://ispyb.diamond.ac.uk/dc/visit/mx26568-3/id/4893489


![image](https://user-images.githubusercontent.com/30625594/89537524-60d6c700-d7f1-11ea-9e87-0a593967efc0.png)
![image](https://user-images.githubusercontent.com/30625594/89537547-67fdd500-d7f1-11ea-8bef-977627a80339.png)
Summary
Anomalous signal looks much better in xia2-3dii (predicted ep success of 98% vs 33%) however neither dataset satisfactorily phases (both complete, but R factors ~ 0.5). Dimple results significantly better for xia2-dials (fast_dp seems better still). Suggests dataset has some issues independent of the choice of data processing program?

Details

- xia2-dials ep_predict ``` {
"success": 33.208, "failure": 66.792,
"threshold": 80.0, "class": 0, 
"metrics": {
	"Low resolution limit": "68.51418", 	"Anomalous slope": "0.40226", 
	"Anomalous correlation": "0.12728", 	"dI/s(dI)": "0.50436", 
	"dF/F": "0.09606", 
	"f\"": "5.77000”
}}```
- xia2-3dii ep_predict ``` {
"success": 98.122, "failure": 1.878, 
"threshold": 80.0, "class": 1, 
"metrics": {
	"Low resolution limit": "64.78000", 
	"Anomalous slope": "1.14135", 
	"Anomalous correlation": "0.58041", 
	"dI/s(dI)": "1.22852", 
	"dF/F": "0.10860",
	 "f\"": "5.77000”
}}```
- xia2-dials big_ep ``` Overall best on cycle 8   R= 0.47  
Rfree= 0.54
Residues built: 140    Side chains: 0
Model-map correlation: 0.5  
Resolution:  2.3```
- xia2_3dii big_ep ``` Overall best on cycle 2   R= 0.54  Rfree= 0.57
Residues built: 109    Side chains: 0
Model-map correlation: 0.45  
Resolution:  2.55```
- xia2-dials dimple ``` overall_r: 0.1916, free_r: 0.2733 ```
-  xia2-3dii dimple ```overall_r: 0.2404 , free_r: 0.3043```

**Comment by jbeilstenedmands** [comment]
**Thaumatin Dataset** (number 10 above) https://ispyb.diamond.ac.uk/dc/visit/cm26459-6/id/5059090

![image](https://user-images.githubusercontent.com/30625594/89539270-78af4a80-d7f3-11ea-8c40-c5abf47408d1.png)
![image](https://user-images.githubusercontent.com/30625594/89539318-8369df80-d7f3-11ea-9415-69d3c4f07184.png)
Summary
Anomalous signal looks a bit better for xia2-3dii, particularly at mid resolution. However, big_ep and dimple give slightly better results for xia2-dials (difference noticeable in Rfree). This dataset shows improved anomalous metrics for xia2-dials compared to when first looked at (May 2020), however that was also able to phase using big_ep triggering manually. Conclusion is that this dataset is not an issue from an anomalous signal perspective.

Details

- xia2-dials ep_predict ``` {
"success": 71.708, "failure": 28.292,
"threshold": 80.0, "class": 0,
"metrics": {
	"Low resolution limit": "54.19498",
	"Anomalous slope": "0.37257", 
	"Anomalous correlation": "0.27588",
	"dI/s(dI)": "0.48916", 
	"dF/F": "0.04863", 
	"f\"": "0.53265”
}}```
- xia2-3dii ep_predict ``` {
"success": 95.957, "failure": 4.043, "threshold": 80.0, "class": 1, 
"metrics": {
	"Low resolution limit": "45.95075", 	"Anomalous slope": "1.07113", 	"Anomalous correlation": "0.35007", 	"dI/s(dI)": "0.98786", 
	"dF/F": "0.04500", 
	"f\"": "0.53265”
}} ```
- xia2-dials big_ep ``` Overall best on cycle 4   R= 0.21   Rfree= 0.22
Residues built: 205    Side chains: 205
Model-map correlation: 0.82  
Resolution:  1.38 ```
- xia2-3dii big_ep ``` Overall best on cycle 1   R= 0.21   Rfree= 0.24
Residues built: 199    Side chains: 199
Model-map correlation: 0.8  
Resolution:  1.42```
- xia2-dials dimple ``` overall_r: 0.1663, free_r: 0.1782 ```
- xia2-3dii dimple ```overall_r: 0.1537, free_r: 0.1829```

**Comment by dagewa** [comment]
Thanks James, this is very helpful. (4) is intriguing. Maybe @isikhar might be able to comment on why the big_ep paths diverge so much for datasets that look very similar, on the face of it. (2) might be worth some manual poking to see what is "wrong" with the dataset. Perhaps it isn't a good example for comparisons, but it would be good to know why.

**Comment by jbeilstenedmands** [comment]
**Second Thermolysin Dataset** (number 8 above) https://ispyb.diamond.ac.uk/dc/visit/mx26592-2/id/4854111

This dataset has shown a regression in the anomalous signal between a recent nightly version (3.dev.149-g6a7d752e2) and dials v2.1.3.

![image](https://user-images.githubusercontent.com/30625594/89574419-060a9300-d824-11ea-936e-f978bf3b8399.png)
![image](https://user-images.githubusercontent.com/30625594/89574438-0b67dd80-d824-11ea-8054-aedaf27faafc.png)

Running the current version of `dials.scale` on the integrated data from xia2-dials v2.1.3, gives a similarly good anomalous correlation (0.594), so the difference seems to be in the integrated intensities rather than changes in the scaling code. The big_ep run using the current xia2-dials has not (yet) completed but I'm not hopeful. xia2-3dii big_ep completed fine, and the dimple runs for both pipelines look similar. So this looks like it's worth further investigation as to what has changed in the dials processing.

Details:
- xia2-dials ep_predict ```{"success": 12.313, "failure": 87.687, "threshold": 80.0, "class": 0, "metrics": {"Low resolution limit": "80.84477", "Anomalous slope": "0.47027", "Anomalous correlation": "-0.03447", "dI/s(dI)": "0.76557", "dF/F": "0.07466", "f\"": "3.63405"}}```
- xia2-3dii ep_predict ```{"success": 57.271, "failure": 42.729, "threshold": 80.0, "class": 0, "metrics": {"Low resolution limit": "80.47974", "Anomalous slope": "1.26182", "Anomalous correlation": "0.82447", "dI/s(dI)": "1.66330", "dF/F": "0.04071", "f\"": "3.63405"}}```
- xia2-dials 2.1.3 ep_predict ```{"success": 39.883, "failure": 60.117, "threshold": 80.0, "class": 0, "metrics": {"Low resolution limit": "80.83187", "Anomalous slope": "0.34982", "Anomalous correlation": "0.68477", "dI/s(dI)": "0.60720", "dF/F": "0.04689", "f\"": "3.63405"}}```
- xia2-dials big_ep: not (yet) run, not hopeful for a solution
- xia2-3dii big_ep: ```Overall best on cycle 6   R= 0.25   Rfree= 0.29
Residues built: 310    Side chains: 310
Model-map correlation: 0.8  
Resolution:  1.91```
- xia2-dials dimple ```overall_r: 0.2158, free_r: 0.2593```
- xia2-3dii dimple ```overall_r: 0.2087 free_r: 0.2495```
