### ISSUE TITLE
Experiments contain hard-coded references to external pickle files

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1238]
The following is frequently a problem in the context of running dials through xia2 at Diamond:
```
$ dials.image_viewer /dls/i04/data/2020/cm26459-2/processed/20200331/TestThaumatin/sethau_9/sethau_9_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_SAD_SWEEP1.{expt,refl}
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  reflections = /dls/i04/data/2020/cm26459-2/processed/20200331/TestThaumatin/sethau_9/sethau_9_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_SAD_SWEEP1.refl
}

Sorry: Unable to handle the following arguments:
  "/dls/i04/data/2020/cm26459-2/processed/20200331/TestThaumatin/sethau_9/sethau_9_1_/xia2-dials/DataFiles/AUTOMATIC_DEFAULT_SAD_SWEEP1.expt" failed during ExperimentList processing:
    Traceback (most recent call last):
      File "/dls/science/users/hko55533/software/cctbx_py3/modules/dials/util/options.py", line 333, in try_read_experiments
        self.experiments.append(converter.from_string(argument))
      File "/dls/science/users/hko55533/software/cctbx_py3/modules/dials/util/phil.py", line 43, in from_string
        s, check_format=self._check_format
      File "/dls/science/users/hko55533/software/cctbx_py3/modules/dxtbx/model/experiment_list.py", line 708, in from_json_file
        infile.read(), check_format=check_format, directory=directory
      File "/dls/science/users/hko55533/software/cctbx_py3/modules/dxtbx/model/experiment_list.py", line 698, in from_json
        directory=directory,
      File "/dls/science/users/hko55533/software/cctbx_py3/modules/dxtbx/model/experiment_list.py", line 683, in from_dict
        obj, check_format=check_format, directory=directory
      File "/dls/science/users/hko55533/software/cctbx_py3/modules/dxtbx/model/experiment_list.py", line 353, in decode
        imageset = self._imageset_from_imageset_data(imageset_data, models)
      File "/dls/science/users/hko55533/software/cctbx_py3/modules/dxtbx/model/experiment_list.py", line 198, in _imageset_from_imageset_data
        mask_filename, mask = self._load_pickle_path(imageset_data, "mask")
      File "/dls/science/users/hko55533/software/cctbx_py3/modules/dxtbx/model/experiment_list.py", line 176, in _load_pickle_path
        with open(filename, "rb") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/dls/i04/data/2020/cm26459-2/tmp/zocalo/20200331/TestThaumatin/sethau_9/sethau_9_1_/e1ccc2de-2969-40f5-a0be-6a3f466d242d/xia2-dials/DEFAULT/SAD/SWEEP1/index/2_hot_mask_0.pickle'
```

1. At the end of a xia2 job, it copies the integrated experiment and reflection files from (e.g.) `DEFAULT/SAD/SWEEP1/index/` to `DataFiles`, but does not copy the referenced hot pixel mask (in fact it doesn't, or shouldn't, necessarily need to know about this external file).
2. At Diamond, we initially run xia2 (via zocalo) in a temporary directory, before copying a subset of the results (including the `DataFiles` directory, but not the `DEFAULT` directory) to the visit `processed` directory.
3. The copied experiment files continue to work e.g. with dials.image_viewer until the files in the temporary directory are wiped.
4. I don't think that either xia2 or zocalo should need to know about, or manage, any external files referenced by the experiment.

**Comment by graeme-winter** [comment]
This is potentially the entrance to an infinitely deep rabbit hole, but I wonder if we should be serialising experiments to JSON or whether we could do something like a MIME formatted document which starts with the experiment JSON blob as it exists already but allows extended objects to be encapsulated further down? So that way we would be able to encode the auxiliary data in later parts. Would also help for storing "bigger" things like spectra which are not obviously well suited to storing as text documents.

**Comment by dagewa** [comment]
HDF5?

**Comment by graeme-winter** [comment]
True, but that opens another pot of worms which looks like:

Oh, HDF5 - this should be a NeXus specification -> long and drawn out specification process -> have to use NXmx to describe everything -> .... 

HDF5 container would work fine, we can dump a string dataset into it 🙂

But it would also lose the ability to look at the file with less, which if memory serves would work with MIME, as well as the MIME only having one part in most cases (e.g. where we don't have masks)

But I do see your point. 

Obviously this will again raise the question why are we not using HDF5 for the reflections, then we could actually store everything in the one file. &c. 

Then much further introspection and discussion ensues, which is again not wrong. But arriving at a conclusion before the heat death of the universe would be a good thing.

**Comment by Anthchirp** [comment]
We could have a dials.edit_my_file command that extracts the string, calls $EDITOR, and then writes back any changes. Similar to how `git commit --amend` etc. works

**Comment by graeme-winter** [comment]
Alternatively - thinking some more about this - since we already use messagepack for the data files could we not also use messagepack for the models etc.?

I guess we could reframe the discussion here as - 

 - we believe that the experiment descriptions should be self contained
 - we believe we should not be using pickle files 
 - we believe they should be portable i.e. if you move results to another folder they should still work

If we agree with the above statements that sets the discussion into a sensible starting position. 

We then have opportunity for further discussion - 

 - should the model and data be in the same files? or have this as an opportunity - see previous conversations about reflex [portmanteau - refl + expt]
 - user tools to separate / combine models and data could then follow

Derivations - 

 - experiments are self contained -> masks etc. are included in there -> needs to be a binary container format -> messagepack or h5
 - we believe we should not be using pickle files -> we need to migrate mask.pickle to mask.h5 or mask.mpack anyways
 - we believe they should be portable i.e. if you move results to another folder they should still work -> if they are self-contained then there is no need to have any path in there beyond the accessor string for the raw data

... discuss 😉

**Comment by graeme-winter** [comment]
FWIW the more words I type on this topic, the more I think there has to be a very good argument _not_ to move everything to HDF5, though I really, really, *really* want to make sure this does not become a NeXus file for the _working_ data since we will then lose 100% of our ability to extend / modify / change things - am happy that something NeXus-like is the answer for export / archive.

**Comment by phyy-nx** [comment]
I really think it should be NeXus, but I don't want folks to think that is limiting.  There's lots of dials-specific stuff that can be just 'tacked on' to any NeXus file we want.  As we think we are adding things that should be standardized, we can push them through the NIAC.  

Importantly, and I think it's really worth stressing this, we already have code that serializes an entire ExperimentList to NeXus anyway.  I think the only limiting problem is shoeboxes, which are ragged arrays.

**Comment by graeme-winter** [comment]
Specific use case: spot finding - we go find spots - therefore we have columns:

```
bbox
flags
id
intensity.sum.value
intensity.sum.variance
n_signal
panel
shoebox
xyzobs.px.value
xyzobs.px.variance
```

Looking at https://manual.nexusformat.org/classes/base_classes/NXreflections.html - h, k, l are mandatory, shoebox is not described. I can see the dials provenance in NXreflections as a lot of the names are familiar, if mangled to be single columns since you cannot define a vec3<double> or vec3<int> in NeXus

_However_ - and this is a massive one - you see these names? You know these names, you have been using these names for years, and they are coded into every piece of code out there. These names *_must not_* change. 

Exporting reflection data is fine, but for working data? Nope. The names in the file should conform to the object names as they do today. Mangling / demangling will kill us. The working data in DIALS are to make DIALS work, not for the NIAC to tell us how to use. 

I note that the NIAC specification *should* be updated to include definitions from scaling, but this is a separate issue.

**Comment by phyy-nx** [comment]
It’s a reasonable point. I don’t see a way to do a working reflections format in nexus without using a concordance of some kind.  However, that concordance is already written, for both reflections and experiment lists (with the exception of shoeboxes). Otherwise dials.export and wouldn’t work. 

-Aaron

**Comment by graeme-winter** [comment]
> It’s a reasonable point. I don’t see a way to do a working reflections format in nexus without using a concordance of some kind. However, that concordance is already written, for both reflections and experiment lists (with the exception of shoeboxes). Otherwise dials.export and wouldn’t work.

So, direct map for working data, concordance for export would make the problem go away? I continue to think that enforcing external standards for our working data which will never be archived is not useful - for the output, at the end of processing, which is supposed to be somehow understood in the future I agree. Intermediate files are - from a certain perspective - a workaround to address the limitations of not having persistent memory.

**Comment by phyy-nx** [comment]
Right, a concordance is all we need. Plus we can add whatever we want without having to go through the NIAC. The important thing is that it’s not actually very much work to fit a standard when we move to hdf5. 

-Aaron

**Comment by graeme-winter** [comment]
I think you missed what I was saying

 - our names for working files, precisely as in mpack
 - NeXus for export

Two worlds, two problems, both happen to share HDF5 container format

**Comment by graeme-winter** [comment]
OK, so some further observations on this - spent some time looking at storing experiments in HDF5 as a hack to see if the topology works - https://github.com/cctbx/dxtbx/tree/experiment-as-hdf5 - and it is a lot harder than you may think.

This is because HDF5 is designed to store _data_ which it does very well, and our experiment model is a tiny amount of data with a lot of class structure & relationship information - what JSON does well since this is an object model, and what HDF5 does badly. 

What HDF5 would do well is store the "ancillary data" like masks and spectra and so on - however should we be storing that in the experiment model? It is static so will be copied for every step. If the mask happened to be 3D (which is perfectly possible [1,2]) we could be making a lot of copies. Aha! But HDF5 allows external references right? Except then it is not encapsulated.

So I think this is more complex than at first thought, and maybe where we are at the moment is not as bad as it seems. Moving away from pickle would be good, improving the tooling would be good, saving the ancillary data would be good, but I am not sure we should be keeping it all in one file. ~ 200ks exploratory effort went into the mapping in the branch & showed me it is more complex than may at first seem. 

[1] dynamic shadow calculation
[2] recovery time for integrating PAD - so after overload requiring > 1 frame to recover full sensitivity for continuous readout

**Comment by phyy-nx** [comment]
Hi all, I did some tinkering with this too.  In [dials/util/nexus](https://github.com/dials/dials/blob/master/util/nexus/__init__.py) there are two functions, dump and load, which take ExperimentList objects and serialize/deserialize them to HDF5 using NeXus.  I modified the from_file/to_file methods of ExperimentList to use these methods instead and, with some minor bugfixes, it showed promise.  I was able to run dials.import on a dataset and it output a NeXus file that represented it.  The only thing missing is the image set object which doesn't have a natural equivalent in NeXus, therefore deserialization didn't work yet.  That would be one area we'd need to use something custom to DIALS in NeXus.

I don't agree that HDF5 stores hierarchical meta data badly.  It looks the same as a JSON file when I use HDFView, and is way easier to navigate.  Anyway I wouldn't reject this idea out of hand as I was _very nearly there_ with only an hour and a bit of investigation.

**Comment by graeme-winter** [comment]
@phyy-nx sounds like you approached this from a different tack - given your code you have for creating NeXus files from streams of data taken from various X-FEL sources, I can see that saving the metadata in NeXus format should be relatively do-able.

Two observations - neither meant to be criticism 🙂 - 
 - I was approaching this as a drop-in replacement which really didn't mesh - HDF5 has no representation for a dictionary of complex types (I was trying to re-use as much as possible of the existing machinery)
 - This does not avoid some of the more fundamental issues with the idea listed in https://github.com/dials/dials/issues/1238#issuecomment-615572105 - specifically I am not sure we _want_ to serialise everything since this could include duplicating e.g. masks etc. 

Clearly HDF5 allows us to reference data in other files, so the latter can be avoided by using this feature, however that takes us around full circle to the issue above, with the replacement of the word "pickle" with HDF5. 

I continue to be nervous about aligning our fundamental serialised data format with NeXus since this does constrain our choices and mean that there is not a 1:1 mapping between the serialised version of the data structure and the data structure we are using in memory (i.e. it is an import / export process rather than a serialisation.)

In an admittedly long-winded way I am proposing we use HDF5 to store "large / ancillary binary data" and continue to use JSON for our experiment files. The number of times I have eyeballed the files themselves (obviously via `vi` or similar) is not small and the advantage of being able to change the models with a text editor I think is substantial. If we can figure out a way of natively referring out to HDF5 for masks, spectra etc. I think we would be home and dry. Adding a tool to update experiments when they are moved would be useful I think in helping to work around the original question.

**Comment by graeme-winter** [comment]
We could probably grab an iselection of invalid values for this (i.e. !mask, since mask True is good) & just stream to output? I note a case @benjaminhwilliams just stumbled across where the mask being absent was a problem had a total of 0 bad values i.e. it contained no signal (so if we find no bad pixels we should not link the file in the first place)

**Comment by graeme-winter** [comment]
Taking a quick look at intercepting the writing of a pickle to instead save `list((~data).iselection())` - down as far as `imageset_ext.cc` looking at `ExternalLookup` pickling 🐇🕳

**Comment by graeme-winter** [comment]
This may be stale but it is still an issue 🙄
