### ISSUE TITLE
dials.index permutes axes from unit_cell but not space group

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#125]
dials.index permutes provided axes but not the space group. Thus, it ends up assigning wrong axes as screw-axes.

In the example below, I want to have 67.6,346,98,90,90,90 P21 21 2 (the c-axis (98) as the non-screw axis). But DIALS ends up in 67.8,346.7,98.1,90,90,90 P21 2 21. making the b-axis (346) as the non-screw axis.

```
$ dials.index datablock.json strong.pickle space_group=P21212 unit_cell=67.6,346,98,90,90,90 indexing.method=fft3d verbosity=3

DIALS 1.dev.194-gc758758
The following parameters have been modified:

indexing {
  known_symmetry {
    space_group = "P 21 21 2"
    unit_cell = 67.6 346 98 90 90 90
  }
}
verbosity = 3
input {
  datablock = datablock.json
  reflections = strong.pickle
}

Target symmetry (reference setting):
Unit cell: (67.6, 98, 346, 90, 90, 90)  # <= should be 67.6,346,98
Space group: P 21 21 2 (No. 18)         # <= OR this should be P 21 2 21

Target symmetry (primitive cell):
Unit cell: (67.6, 98, 346, 90, 90, 90)
Space group: P 21 21 2 (No. 18)

...

RMSDs by experiment:
---------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_Z   |
| id  |      | (px)    | (px)    | (images) |
---------------------------------------------
| 0   | 3082 | 0.18161 | 0.16854 | 0.11456  |
---------------------------------------------
Target d_min_final reached: finished with refinement
Final refined crystal models:
model 1 (3564 reflections):
Crystal:
    Unit cell: (67.828, 346.691, 98.058, 90.000, 90.000, 90.000)
    Space group: P 21 2 21
    U matrix:  {{ 0.9643, -0.2273, -0.1361},
                { 0.0682, -0.2835,  0.9566},
                {-0.2560, -0.9317, -0.2578}}
    B matrix:  {{ 0.0147,  0.0000,  0.0000},
                { 0.0000,  0.0029,  0.0000},
                { 0.0000,  0.0000,  0.0102}}
    A = UB:    {{ 0.0142, -0.0007, -0.0014},
                { 0.0010, -0.0008,  0.0098},
                {-0.0038, -0.0027, -0.0026}} 
```

**Comment by rjgildea** [comment]
This is a problem because dials.index is attempting (and failing) to be clever by trying to figure out the correct combination of unit cell and space group setting. It is using code in the cctbx to do this (the same code as used by iotbx.lattice_symmetry), however this is working on the metric symmetry - Pmmm in this case. I will try to find a better fix for this problem, however in the meantime you should be able to use the workaround of indexing in P222, then running dials.reindex experiments.json indexed.pickle and setting the appropriate values of the change_of_basis_op and space_group parameters.

**Comment by biochem-fan** [comment]
I confirmed that it works for my dataset above. Thank you very much.
