### ISSUE TITLE
ImportError: resource

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1251]
test of CCP4's DIALS 2.2.3 build on Windows fails with
```
ImportError while importing test module 'C:\msys64\je\workspace\CCP4\win10-trunk\devtools\test-install\lib\py2\site-packages\dials\test\command_line\test_integrate.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
..\lib\py2\site-packages\dials\test\command_line\test_integrate.py:10: in <module>
    from dials.algorithms.integration.processor import _average_bbox_size
..\lib\py2\site-packages\dials\algorithms\integration\processor.py:8: in <module>
    import resource
E   ImportError: No module named resource
```

Looks to be UNIX-like only
https://stackoverflow.com/questions/37710848/importerror-no-module-named-resource

**Comment by Anthchirp** [comment]
Okay, we can't use `psutil`, because psutil [only offers resource limits](https://github.com/giampaolo/psutil/issues/831) on linux with [kernel>=2.6.36 and glibc>=13](https://github.com/giampaolo/psutil/blob/e1ea2bccf8aea404dca0f79398f36f37217c45f6/psutil/_psutil_linux.c#L45-L49). The conda-forge build of psutil is built [on a docker container](https://github.com/conda-forge/psutil-feedstock/blob/426d92dc5c374f05bdd1d0f98248822788100397/.azure-pipelines/azure-pipelines-linux.yml#L13-L16) that runs [CentOS 6](https://github.com/conda-forge/docker-images/blob/0b8d9f4d9f31728634cfcce82aaec4cd617c8513/linux-anvil-comp7/Dockerfile#L1), which means glibc=2.12 and kernel=2.6.32. Thus no rlimit on conda-forge psutil.

**Comment by graeme-winter** [comment]
Possibly we should just ignore the memory checks on Windows then? Seems like the least worst solution.

**Comment by Anthchirp** [comment]
no, there is a better solution. still working on this.

**Comment by graeme-winter** [comment]
👍 will stop interfering 🙂

**Comment by Anthchirp** [comment]
First wanted to complete the report to CF in https://github.com/conda-forge/psutil-feedstock/issues/47 :wink:
