### ISSUE TITLE
Please use `tqdm.std.*` instead of `tqdm._tqdm.*`

### ISSUE THREAD

**Issue by picca** [dials/dials#1255]
Hello, while working on the Deban package of dials, I got this error message during the pytest execution.

```
monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f3dce2c7190>

    @pytest.fixture
    def time(monkeypatch):
        "Fixture to monkeypatch the tqdm time access"
        ft = FakeTime()
>       monkeypatch.setattr(tqdm._tqdm, "time", ft)
E       AttributeError: module 'tqdm' has no attribute '_tqdm'

/usr/lib/python3/dist-packages/dials/test/util/test_progress.py:62: AttributeError
```

When I import tqdm._tqdm, I have this message

```
>>> import tqdm._tqdm
<stdin>:1: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.std.*` instead of `tqdm._tqdm.*`
```

**Comment by ndevenish** [comment]
Hi Picca,

As per our dependency list: https://github.com/dials/dials/blob/9f591ba10e29f89b1a17285cba043cb15254d100/libtbx_config#L21

we don't support that version of `tqdm`, and are pinned because we use internal features. It might be possible to switch versions if the feature still works, but we haven't tested that version. If everything still works fine with a newer version, we're happy to accept a change to it.

Alternatively, I'd be open to dropping this code and just using tqdm directly if it's noninteractive behaviour is acceptable now (this code was so that we could _not_ have the noisy progress bar for short runs)

**Comment by Anthchirp** [comment]
I believe removal of the custom core is the reasonable way forward, cf. #1328
