### ISSUE TITLE
Integrate from cycling centroids

### ISSUE THREAD

**Issue by jmp1985** [dials/dials#132]
Currently fails due to lack of shoeboxes in integrated output.

**Comment by graeme-winter** [comment]
Easily resolved if you want to. https://github.com/xia2/xia2/issues/44 Has details.

**Comment by graeme-winter** [comment]
@jmp1985 only additional comment as referenced in that xia2 ticket is that the reflection profile parameter code does not seem to work quite right - it gives much wider profiles. Wonder if this is because the pixels are not flagged in the shoeboxes if we extract them after integration i.e. don't know which should be the peak etc. Have added code which should subtract the background from the shoeboxes so in principle _should_ be better... perhaps interesting to take a look at?

**Comment by dagewa** [comment]
Did this make it into DIALS 1.4? Can this be closed?

**Comment by dagewa** [comment]
I'll assume it can.
