### ISSUE TITLE
Parallelise outlier rejection in refinement

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1427]
Outlier rejection in refinement is done independently for reflections split by experiment (if `seperate_experiment=True`), by panel (if `separate_panels=True`) and by phi (depending on `block_width`). This can potentially lead to a large number of independent outlier rejection jobs, especially in the case of multi-panel detectors, which can significantly increase (and dominate) the runtime (see #1424). This seems an embarrassingly parallel task for which it should be possible to get significant performance increases.

https://github.com/dials/dials/blob/414c84f0b7cde2effcc50b3af2ed813da9c6c05d/algorithms/refinement/outlier_detection/outlier_base.py#L74-L270

**Comment by dagewa** [comment]
It's a good idea. I guess the right approach is using `concurrent.futures.ProcessPoolExecutor`, based on other DIALS programs. At the moment `dials.refine`'s `nproc=1` because for NLLS engines increasing this tends to hinder not help. Maybe making this `Auto` as default and then setting for outlier rejection only using the mechanism described in #1408 would be okay
