### ISSUE TITLE
best_unit_cell in MTZ output

### ISSUE THREAD

**Issue by dagewa** [dials/dials#1440]
`dials.scale` and `dials.export` both have a `best_unit_cell` parameter for resolution cutting. In the case of `dials.export` this also controls the overall resolution of the output MTZ, but this does not occur for either the unmerged or merged MTZs that can be produced directly by `dials.scale`. This seems inconsistent. Furthermore, `dials.merge` does _not_ have this parameter. This means that while it is possible to produce an unmerged MTZ with a particular cell in DIALS (by using `best_unit_cell` in `dials.export`) it is not currently possible to produce a merged MTZ with a particular cell.

**Comment by jbeilstenedmands** [comment]
When investigating this issue, I found that the unmerged mtz file produced by dials.scale _does_ use the best unit cell given, and this (should be) covered by the test `algorithms\scaling\test_scale.py::test_scale_best_unit_cell_d_min`. Could I ask you recheck what you were seeing in your example case, and if there is perhaps a different bug then I can investigate that, but this shouldn't be the issue here.

**Comment by dagewa** [comment]
Yes, sorry, you are right. It is only the _merged_ MTZ it outputs that does not use the best unit cell.
