### ISSUE TITLE
Spotfinding overhead computing resolution map

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#1587]
During spotfinding with a `d_min` or `d_max` filter set, there is an expensive overhead computing a map of the resolution at each pixel:

https://github.com/dials/dials/blob/9711b078f8837f9b20064529caf0f6fa0f9ef10f/util/masking.py#L184-L187

For an EIGER 16M constructing the resolution map can take an additional ~2.8 seconds compared to ~1.6 seconds total for spotfinding if no resolution limits have been specified.

During standard spotfinding (i.e. on a full imageset) this is only done once, so the overhead is not significant compared to the time taken to spotfind an entire dataset. The resolution map is also cached for given beam and panel models to alleviate this to some extent in the case of per-image analysis (see #1177).

However, in the context of per-image analysis at Diamond, this still results in a significant overhead. For example, we may perform PIA on 250 image files selected from a rotation scan, and these are spread randomly across 80 PIA service instances, with each instance seeing ~3-4 images. This means that the additional overhead will affect the processing time of around 1/4 to 1/3 of all images.

**Comment by phyy-nx** [comment]
FWIW, in SFX data, where the wavelength changes for each image, the d_min/d_max masking changes slightly for each image.  Because of the mask generation overhead that you mention here, I usually use dials.generate_mask on a single image with resolution limits a bit beyond what I want, then use that mask for spotfinding.  It skips the per-pixel calculation of `s1` and runs much faster.  I then limit the spots used in indexing using indexing d_min/d_max limits.

**Comment by ndevenish** [comment]
I think this issue exists outside of DIALS, in our live analysis services, and we can address this there.
