### ISSUE TITLE
for large list of ids dials.reciprocal_lattice_viewer does not show view space

### ISSUE THREAD

**Issue by elena-pascal** [dials/dials#1605]
For more than maybe few 10 ids the list becomes too large for the view screen on the right to fit in the window. This is what it looks like for 100. Looking at 1k ids (not sure how common a use case this is) makes it impossible to see the view space.
![rec_space_view](https://user-images.githubusercontent.com/30300213/108842635-79fa6600-75d1-11eb-8a96-90d99893a0d0.png)

**Comment by elena-pascal** [comment]
There are other bits perhaps related to this:
1) clicking on the buttons has no effect for me
2) the range of ids starts at -1 (?) but it is also not what I'm looking at. If I filter for just ids 20 and 30, in the view I get all the buttons [-1:30] but I do have only two datasets in the plot.

**Comment by dagewa** [comment]
This is for @graeme-winter's 7000+ image grid scan, I think. I suppose people haven't really tried using `dials.reciprocal_lattice_viewer` on still series before, because with random orientations you'd just get powder diffraction shells. But that is exactly what we are interested in here. So, perhaps `dials.reciprocal_lattice_viewer` _should_ work for still series, and at the very least it should avoid trying to draw 7000 buttons...

**Comment by graeme-winter** [comment]
Suggest:
- parameter for max experiment switches (like, 20?)
- if > this, show none
- have a "text" box instead & some filter like 1-30 or 99,100,101
Welcome other alternatives

If indexed this will be more useful as can show in crystal frame

**Comment by dagewa** [comment]
Ah yes, the crystal frame view will make the reciprocal lattice viewer for stills quite useful.
