### ISSUE TITLE
Why can't I import dxtbx from console entry point script?

### ISSUE THREAD

**Issue by dsclassen** [dials/dials#1749]
I have used the bootstrap installed to setup the DIALS conda env

I have installed my development project (ispyb-populate) using `pip install -e .`

If I run either `python` or `dials.python` from the command line and type: `import dxtbx` it works.

However, when I run my custom console script it does not. I have printed out a few `sys` variable immediately after the `import sys` in order to see what's up. It looks to me like the DIALS bootstrap python is being used and that the various `dials-bootstrap/conda_base/lib` directories are in the discovery path so why is it unable to import dxtbx?

```
3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) 
[GCC 9.3.0]
sys.version_info(major=3, minor=8, micro=10, releaselevel='final', serial=0)
/home/classen/projects/ispyb/dials-bootstrap/conda_base/bin
/home/classen/projects/ispyb/dials-bootstrap/conda_base/lib/python38.zip
/home/classen/projects/ispyb/dials-bootstrap/conda_base/lib/python3.8
/home/classen/projects/ispyb/dials-bootstrap/conda_base/lib/python3.8/lib-dynload
/home/classen/projects/ispyb/dials-bootstrap/conda_base/lib/python3.8/site-packages
/home/classen/projects/ispyb/dials-bootstrap/modules/xia2/src
/home/classen/projects/ispyb/ispyb-populate/src
Traceback (most recent call last):
  File "/home/classen/projects/ispyb/dials-bootstrap/conda_base/bin/tweek-data", line 33, in <module>
    sys.exit(load_entry_point('ispyb-populate', 'console_scripts', 'tweek-data')())
  File "/home/classen/projects/ispyb/dials-bootstrap/conda_base/bin/tweek-data", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/classen/projects/ispyb/dials-bootstrap/conda_base/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/classen/projects/ispyb/dials-bootstrap/conda_base/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/classen/projects/ispyb/ispyb-populate/src/ispyb_populate/data_tweeker.py", line 24, in <module>
    import dxtbx
ModuleNotFoundError: No module named 'dxtbx'
```

**Comment by Anthchirp** [comment]
This is because of a design decision in cctbx that we unfortunately are tied to. Cctbx modules (such as dxtbx or dials) do not behave like Python packages (like xia2).

I recently described this in more detail in different context at https://github.com/cctbx/dxtbx/pull/382#issuecomment-859923323, where I also outline the solution: you need to declare (and install) a further entry point per every console script in your package, _then_ re-run `libtbx.refresh`/`make reconf` (and then possibly run `hash -r`, or open a new shell due to caching effects).

We may at some point in the future be able to fix this on the dxtbx/dials side of things, but since this involves turning both packages from cctbx modules into python packages this will unfortunately take some time. Having said that, I am very happy to hear there is demand for this at ALS/LBL, as this demonstrates that this work would not just be an academic exercise but instead would provide a tangible benefit to our user community.

**Comment by Anthchirp** [comment]
For dxtbx specifically: You can now install dxtbx as a native conda package directly from conda-forge. That way dxtbx will behave like a normal python library (because it is).

Work is still ongoing to achive the same for DIALS, but that will take some time.

If there is anything else we can help with in the meantime, please reopen or open a new ticket
