### ISSUE TITLE
`dials.image_viewer` is slow when stacking 

### ISSUE THREAD

**Issue by elena-pascal** [dials/dials#1776]
This is especially true when stacking thousands of images which would be something useful for serial data.
It would be nice to have more than one processor working on what would be an embarrassingly parallel task or, alternatively, have some caching solution. This could probably be in discussion.

**Comment by graeme-winter** [comment]
I think a trivially parallel stack all type option would be simple enough. Caches have a habit of causing issues, as you recently found 🙂

**Comment by toastisme** [comment]
Once you have stacked images, doing _anything_ is slow because `stack_images` is [called](https://github.com/dials/dials/blob/main/util/image_viewer/spotfinder_frame.py#L1245) during `update_settings`. If I understand this correctly, the images are re-stacked every time, which surely isn't needed in most cases.
