### ISSUE TITLE
dials.import stdin broken

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#179]
The help suggests that the following should work. It does not.
```
$ find $(libtbx.find_under_build xia2_regression/test_data/X4_wide) -name "X4_wide_M1S4_2_00*.cbf" | dials.import
DIALS 1.dev.527-gc7f7ddd
Sorry: No datablocks found
```

**Comment by graeme-winter** [comment]
I am just starting to take a look at this

**Comment by graeme-winter** [comment]
This was emergent behaviour because the quick_parse flag to parse args ate the stdin first time, then was not there to eat on second pass; now don't read stdin on quick_parse which I think should be the correct behaviour.

Assert: @jmp1985 a better solution would be to have a parser.inspect() which would go through and look at the args on the command-line then parse() which would consume them....

**Comment by jmp1985** [comment]
Hi Graeme, what does quick_parse actually do?

**Comment by graeme-winter** [comment]
i have no idea you added it I assume :)

It *looks like* you use it to check for verbose logging flags & if they are there you change the behaviour of the logging before repeating the parsing process, anyhow it seems to work now && all tests pass
