### ISSUE TITLE
pip install mathplotlib error

### ISSUE THREAD

**Issue by yuyuyoyo** [dials/dials#1905]
![image](https://user-images.githubusercontent.com/85676324/139522659-b54ffced-c1e7-4d92-8763-fb02db12948b.png)

I try to do 

` pip install --upgrade setuptools`
`pip install matplotlib`

still error help me pls

**Comment by ndevenish** [comment]
Hi @yuyuyoyo, this doesn't appear to be an issue with DIALS, as we don't yet support Python 3.10 - we had some issues with numpy which we were waiting to be resolved.

This specifically looks like `matplotlib` binary wheels aren't available for windows yet. `matplotlib` and numpy are somewhat complicated and aren't pure python - there are parts that need to be compiled. Usually, you don't have to deal with this because you can get pre-built packages through pip called a "wheel". If this isn't present (as it isn't yet for windows and python 3.10) then it needs to build itself on your computer, which often needs a whole chain of dependencies. Python 3.10 is pretty new still, and lots of places don't have it working yet (for example, normally we would recommend getting packages through conda, but that also doesn't have matplotlib binaries for 3.10 yet either).

If you want to continue with Python 3.10, I'd suggest looking to see if the issue is discussed at https://github.com/matplotlib/matplotlib somewhere - I am certain that they will be aware of the issue.

**Comment by yuyuyoyo** [comment]
> Hi @yuyuyoyo, this doesn't appear to be an issue with DIALS, as we don't yet support Python 3.10 - we had some issues with numpy which we were waiting to be resolved.
> 
> This specifically looks like `matplotlib` binary wheels aren't available for windows yet. `matplotlib` and numpy are somewhat complicated and aren't pure python - there are parts that need to be compiled. Usually, you don't have to deal with this because you can get pre-built packages through pip called a "wheel". If this isn't present (as it isn't yet for windows and python 3.10) then it needs to build itself on your computer, which often needs a whole chain of dependencies. Python 3.10 is pretty new still, and lots of places don't have it working yet (for example, normally we would recommend getting packages through conda, but that also doesn't have matplotlib binaries for 3.10 yet either).
> 
> If you want to continue with Python 3.10, I'd suggest looking to see if the issue is discussed at https://github.com/matplotlib/matplotlib somewhere - I am certain that they will be aware of the issue.

thanks I done
