### ISSUE TITLE
Do we need phi= setting in reciprocal_lattice_viewer?

### ISSUE THREAD

**Issue by dagewa** [dials/dials#214]
![rlv_funny](https://cloud.githubusercontent.com/assets/11502083/18666795/94e8c5f8-7f25-11e6-8e81-60afc76f216b.png)

See screenshot, i04 BAG training data, with Z range set to [0,5].

I expected to see the beam direction pointing in/out of the image, not across it. Eventually I realised that the datablock starts at 82 degrees, whilst the relps are always displayed at phi=0.

Do we need a phi= setter so that different positions in the scan can be explored in the rlv? Should this default to the start of the scan range, i.e. 82 degrees in this case?

I think this would enhance the utility of rlv as a teaching tool.

**Comment by graeme-winter** [comment]
I.e should show w.r.t datum yes? If you have multiple sweeps I'd think that that is the desired behaviour. That said the positioning of the beam is misleading anyway since it in effect rotates through reciprocal space anyway as you rotate the sample. Hence again showing everything at datum. Beam at angle widget would give you option to reconstruct experiment at given frame number.

**Comment by dagewa** [comment]
> Beam at angle widget would give you option to reconstruct experiment at given frame number

An alternative way of looking at this is that the beam vector display is generally unhelpful. In a 3D view the beam direction is swept out by the scan so showing a particular direction does not give much insight (but may lead to confusion). Also, I'm not sure if the beam direction display works properly when toggling "Show in crystal frame". Rather than trying to show an experiment at a given frame number, we could remove the beam vector display completely and insist that we are trying to show the scan, not its state at a particular frame?

**Comment by jbeilstenedmands** [comment]
Decided: wontfix
