### ISSUE TITLE
dials.image_viewer: stacking messes with trusted_range mask

### ISSUE THREAD

**Issue by dagewa** [dials/dials#2174]
When images are being stacked (unfortunately I hid it in the screencast below, but there's a stack of 5 images), the brightness is not stable. Operating the controls on the settings panel (any of them?) causes the visual brightness to increase, even though the brightness value is not changing. In the screencast I show this by repeatedly toggling `Show predictions`

![stacked](https://user-images.githubusercontent.com/11502083/180398634-f5803c66-577e-4272-98de-77972d8cbc89.gif)

**Comment by dagewa** [comment]
The brightness issue no longer seems to be a problem, but there is still something weird happening. Same test as above. Now we see the mask due to trusted range max including more and more pixels with each redraw

[Screencast from 14-11-24 14:51:52.webm](https://github.com/user-attachments/assets/a701c6f7-74c1-4bb3-9525-c35d3a75ff97)

**Comment by biochem-fan** [comment]
@dagewa
This happens because `stack_images()` [overwrites the image data](https://github.com/dials/dials/blob/main/src/dials/util/image_viewer/spotfinder_frame.py#L1118) of the first frame. When the view setting is updated (e.g. toggling "show predictions" or changing the brightness), [`stack_images()` is called again from `update_settings()`](https://github.com/dials/dials/blob/main/src/dials/util/image_viewer/spotfinder_frame.py#L1489) and adds all other frames into the already-modified first frame. In contrast, toggling "Show mask" or changing the stack number reload the image data and reset the problem.

To fix this, we should call `self.reload_image()` in `update_settings()` or suppress calling `stack_images()` when unnecessary. Unfortunately, simply putting `self.reload_image()` in `update_settings()` causes an infinite loop.

I don't have time to throughly chase the code path at the moment so I leave this observation here.

**Comment by biochem-fan** [comment]
@dagewa
I found a simple trick to force read the image data but this might ignore the per-image mask on the first frame (I am not sure). At least the saturation mask from the first image seems contributing.

```diff
diff --git a/src/dials/util/image_viewer/spotfinder_frame.py b/src/dials/util/image_viewer/spotfinder_frame.py
index 864d7adca..24cbaa0e4 100644
--- a/src/dials/util/image_viewer/spotfinder_frame.py
+++ b/src/dials/util/image_viewer/spotfinder_frame.py
@@ -1078,6 +1078,8 @@ def stack_images(self):
         if self.params.stack_images > 1:
             self.settings.display = "image"
             image = self.pyslip.tiles.raw_image
+            # This clears the cached image data in chooser_wrapper and forces image reload
+            image.set_image_data(None)
             image_data = image.get_image_data()
             if not isinstance(image_data, tuple):
                 image_data = (image_data,)

```

**Comment by dagewa** [comment]
Thanks @biochem-fan, this fixes the immediate issue. Perhaps there are still things that are not optimal regarding masks and stacked frames. For example, if you stack 5 frames should the trusted range be extended 5 times? Whatever the case, this fixes an obvious bug :+1:

**Comment by biochem-fan** [comment]
> For example, if you stack 5 frames should the trusted range be extended 5 times?

A pixel in a stacked view should be shown masked when the pixel is outside the trusted range in *any* of the constituting images, as discussed in https://github.com/dials/dials/issues/1512#issuecomment-753881800.
