### ISSUE TITLE
printable command line reference: access denied?

### ISSUE THREAD

**Issue by murpholinox** [dials/dials#2192]
![Screenshot from 2022-08-04 15-51-35](https://user-images.githubusercontent.com/732802/182950402-00c4b17a-0d72-41c8-b5f9-558016736918.png)
Then I get a gdrive page saying I need to ask for access....

**Comment by rjgildea** [comment]
The issue appears to have been [this google drive link-sharing security update](https://support.google.com/a/answer/10685032?hl=en). I've now fixed this and the document should be visible again. However I note it is rather out of date and could do with updating (e.g. it still refers to `.json` and `.pickle` extensions rather than `.expt` and `.refl` respectively)...
