### ISSUE TITLE
how to obtain dials_regression ?

### ISSUE THREAD

**Issue by picca** [dials/dials#2258]
Hello, I would like to know how to obtain the dials_regression in order to avoid skipping the test
```
tests/algorithms/indexing/test_index.py::test_index_small_molecule_multi_sequence_4 SKIPPED (dials_regression required for this test) [  7%]
```
thanks for your help

Frederic

**Comment by ndevenish** [comment]
Hi Frederik,

I would urge you join our slack at https://dials-support.slack.com/ so that we can talk directly, rather than via a random scatter of support issues. If required, I can send you a direct invite link.

The dials_regression package has been a longstanding pain, in that because of uncertain provenance and licensing of many of the historical data files we can't just open it. We have made efforts to move to https://github.com/dials/data, however progress has been slow.

We're happy to discuss and explain further if you contact us directly.

Nick

**Comment by dagewa** [comment]
`dials_regression` is not public.
