### ISSUE TITLE
dials.refine: please be more imaginative with interval_width_degrees

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#2262]
```
Grey-Area screen19-2 :) $ time dials.refine indexed.* interval_width_degrees=60
Sorry: Ambiguous parameter definition: interval_width_degrees = 60
Best matches:
  refinement.parameterisation.beam.smoother.interval_width_degrees
  refinement.parameterisation.crystal.unit_cell.smoother.interval_width_degrees
  refinement.parameterisation.crystal.orientation.smoother.interval_width_degrees
  refinement.parameterisation.detector.smoother.interval_width_degrees
  refinement.parameterisation.goniometer.smoother.interval_width_degrees
```

To me it seems fairly obvious that in default scan varying refinement I want to set 

```
  refinement.parameterisation.crystal.unit_cell.smoother.interval_width_degrees
  refinement.parameterisation.crystal.orientation.smoother.interval_width_degrees
```

since the others are fixed - however this then means I need to add ~ 100 characters to the command line output (which is admittedly explicit, so good) 

Any chance we could make the more obvious interpretation?

**Comment by dagewa** [comment]
I think the way to do this would be to have another `interval_width_degrees` at the higher level, i.e. `parameterisation` scope. Then make that `expert_level=0` (because the others are all at `1`). That would then get picked automatically with your command line. The behaviour of that one would be to globally set all the others.

I'll do this - just making notes here so I don't forget what to do
