### ISSUE TITLE
Boost 1.78 requires c++14

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#2291]
Hi all, conda, as of yesterday or today, pulls boost 1.78 instead of 1.74.  1.78 seems to require c++14, which dxtbx fails to compile under.

I can reproduce it using the standard installation for developers:
```
wget https://raw.githubusercontent.com/dials/dials/main/installer/bootstrap.py
python bootstrap.py
```

Pinning boost to 1.74 solves the problem for now (see #2292), but it's not a long term solution.

**Comment by graeme-winter** [comment]
Testing now, though this would explain build failures which started appearing yesterday

**Comment by rjgildea** [comment]
It looks like Boost.Geometry requires C++14 from 1.75 onwards:
https://www.boost.org/doc/libs/1_80_0/libs/geometry/doc/html/geometry/release_notes.html

**Comment by ndevenish** [comment]
> seems to require c++14, which dxtbx fails to compile under.

As a point to update this issue - the problem is not dxtbx being incompatible - dxtbx compiles perfectly fine under C++14 - (which it does happily under CMake) it's that the cctbx build system only supports `-std=c++11`, to the point that it will rewrite attempts to force the standard via environment variables.

So this should probably be closed here and reopened in https://github.com/cctbx/cctbx_project.

If there are further dials issues after that, then suggest we reopen once it's actually possible to test.
