### ISSUE TITLE
masking ice rings

### ISSUE THREAD

**Issue by ejfuentes** [dials/dials#2415]
I'm a relatively new user and want to mask ice rings. Not sure how mask specific ice rings. The masking tool will "identify" ice rings, but they don't always align with the ice rings in the data. Is there any way to edit the automatic ice ring feature. I did find a "ring tool" feature, but not sure what it is used for. Finally, I was able to mask the beam stop and save it as "pixels.mask", however I'm not sure what the "mask.phil" file is used for.

Any help would be appreciated. 

Ernie

**Comment by dagewa** [comment]
Hi Ernie

I must admit I've never used the `Ice rings` checkbox within the `dials.image_viewer` mask tool, if this is what you refer to:
![image](https://github.com/dials/dials/assets/11502083/9db0c42e-b8cc-456d-9930-630e5dae2217)

The `Show ice rings` checkbox on the main `Settings` window just shows the powder rings according to hexagonal ice with unit cell 4.498,4.498,7.338,90,90,120. If something else is present, or the detector distance or wavelength are wrong, then these rings won't line up with the data rings.

In any case, I don't try to mask the rings using the `dials.image_viewer` masking tool. You can just use the spotfinding program like this:

```
dials.find_spots imported.expt strong.refl ice_rings.filter=True
```

Other options you can set can be seen in the help printed by `dials.find_spots -hh`

```
    ice_rings {
      filter = False
      unit_cell = 4.498,4.498,7.338,90,90,120
      space_group = 194
      width = 0.002
      d_min = None
    }
```

The `mask.phil` file is just so that you can regenerate the `pixels.mask` file again in a script rather than having to reload the image viewer when processing this data again in future.

```
dials.generate_mask imported.expt mask.phil # creates pixels.mask
dials.apply_mask imported.expt mask=pixels.mask # applies mask to masked.expt
```

**Comment by dagewa** [comment]
Help provided. I don't think there is any reason to keep this open, as much of the image viewer is essentially at WONTFIX status now.
