### ISSUE TITLE
spotfinder gain

### ISSUE THREAD

**Issue by DrTheMick** [dials/dials#245]
spotfinder.threshold.xds.gain=auto should work. It should pass dials.estimate_gain per image or the average for the datablock. Why are gain and global min not auto by default?

**Comment by jmp1985** [comment]
@DrTheMick Currently, this is a manual step:

dials.estimate_gain is called separately from dials.find_spots and the value reported needs to be passed in manually. If "none" is passed in as the gain value (the default) then a gain of 1 is used. 

The global threshold is by default zero which is usually fine for pixel array detectors but CCDs may need different values - finding the "best" value for CCD data sometimes involves trial and error.  

I hope this helps.

**Comment by dagewa** [comment]
The gain calculated by dials.estimate_gain is unrealistic for any detector that has significant correlation between local pixels, like phosphor-taper-CCDs. Because the results may be suspect, we are hesitant to calculate this automatically. There isn't really a foolproof method to determine the gain, although looking at the variance of a single pixel in a region of background down a stack of images is likely to be better than looking at the variance in a region of interest on a single image (as long as background is slowly changing with time or the trend can be removed).

The best approach, of course, is to know the gain from technical specifications of the detector or careful experiments and to write it into the Format class. Whenever this is done, there should be no need for a gain=auto.
