### ISSUE TITLE
dials.refine_bravais_lattice fails for multiple experiments

### ISSUE THREAD

**Issue by dmszebenyi** [dials/dials#2464]
I want to index using two images separated by 90 degrees and determine the probable symmetry. Importing and indexing the two images goes fine, but dials.refine_bravais_lattice on the resulting indexed.expt and indexed.refl results in "dials.algorithms.refinement.DialsRefineConfigError: Experiment id 1 contains no reflections with valid scan angles".

**Comment by dagewa** [comment]
Hi, would you be able to share `indexed.expt` and `indexed.refl`? You could send by email to dials-support@lists.sourceforge.net perhaps.

**Comment by dagewa** [comment]
For reference, the issue here was that the rotation axis is antiparallel to the `fast` direction but dxtbx assumed the inverse. When indexing data from just two images a solution can be found for one of the images, but that solution does not fit the second image. In future this will be handled transparently by providing specific support for CHESS ID7B2 (https://github.com/cctbx/dxtbx/pull/649)
