### ISSUE TITLE
Performance of stills processing from big Eiger datasets

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#258]
Test case is running dials.stills process on 10 images from a 350000 image Eiger dataset.  The dataset is a single master file linked to 350 1000 image subfiles.  Total processing time was 598 seconds, 472 of which were spent in copy.deepcopy, as called by refiner.py in two places on the experiment list.

Feedback from @dagewa: "the use of deepcopy is to avoid side-effects, [...] so the user of refinement can pass in experiments and get back refined_experiments without affecting the original experiments. This way the before and after state can be compared."

Here, the stills indexer isn't comparing before or after, so proposal is to add a parameter to the refiner factory such that the deep copy is optional, and use that parameter for the stills indexer.  Pull request incoming.

**Comment by jmp1985** [comment]
I suspect deepcopy is opening the HDF file each time. This should be addressed during the upcoming dxtbx-refactor

**Comment by ndevenish** [comment]
I see #259 was an attempt to solve this, but ended up not being suitable (see cc6881027370a5c2e7b99bb7e9eacdc7a4705be4).

I've just ran into this by noticing that indexing was taking ~18 minutes on some stills data sets, because of `copy.deepcopy(experiments)` taking 80% of the time at a full *six seconds* per call. After profiling, most of this time is spend copying the `ImageSetData` - for obvious reasons this contains references to every image in the compound file, though it's not opening them, at least any more (as I didn't have the source files on my machine).

Hopefully 624051406ea9b49e0475cb271664e9ca7b8a6324 should be a better fix for this.
