### ISSUE TITLE
Reduce the number of file operations

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#264]
When I run ```strace dials.import /$path/*.cbf``` I find that currently each CBF file is ```stat```ed 5 times and ```open``ed twice. That is 7 file operations per file.
Not a big issue on a local disk drive, but quite a performance hit over networked file systems.

**Comment by Anthchirp** [comment]
This is still the case. We ```stat```x5, ```open```x2, and for the first file ```open```x3

**Comment by ndevenish** [comment]
I've just found this problem again whilst diagnosing the problems opening 100k files. At least one of the stat's comes from `isfile` on every argument (~3min), every file is opened in order to pass to `dxtbx`'s `understand` method, in order to determine file type (~7min), and then *in a separate loop* every file is opened to read the metadata information (~12m). Haven't yet tracked the extra stat's down.

**Comment by Anthchirp** [comment]
We now `open()` the first file twice and every subsequent file once. We don't `stat()` at all. Close to ideal.
