### ISSUE TITLE
Do not use 'Exception' to determine file formats

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#335]
dials.import and dxtbx currently uses _Exception_ exceptions in multiple places to determine whether a file is of a certain format. This will mask any errors and assertions that occur in the import stage even when the format is correct and makes debugging more difficult, see for example #334.

Suggest replacing _Exception_ by a dxtbx _IncorrectFileFormatException_ or similar.

**Comment by jmp1985** [comment]
Hi Markus,

This seems like a good idea. I'll have a look at implementing it.

James

________________________________

**Comment by ndevenish** [comment]
I think I tackled the underlying causes of this a little in e04075ef9, including the separation of validation/other errors. I think this is basically what @Anthchirp was suggesting?

Can close this?

**Comment by Anthchirp** [comment]
Step in the right direction, however I would suggest we should not catch & collect Exceptions during handling, rather just treat them as any other Exception and stop.

**Comment by ndevenish** [comment]
So, @jmp1985 and I discussed this a little and I'm not convinced that it's possible to "fix" properly without a redesign, or at least some imposition of constraints. This is talking about the dxtbx `Registry` and `Format` classes, which is slightly less Exceptiony than the level above which also covers `Datablocks`/`ExperimentLists`.

I guess in ideally every format class `understands` method should return True/False, and every exception is a real error after that. But one problem is that at the moment, the format classes can take almost "anything" as a "filename" - remote, local or just some identifying nonsense string.  I believe that even phil strings might end up trying to be format-identified if not picked up by the parser?

Thus, it's very hard to tell a priori whether an error is because a file is invalid, or a code error, or something else systemic. My first approach e.g. for #503 let through "Sorry" exceptions to catch this but - is the IOError a real system-error that the user should be notified of because the file is missing, or is it a formatting error because it's a phil-parameter that the user mistyped and made it to the parser? See #503, #495 for problems handling this specific situation.

Thus, my former (admittedly imperfect) approach where I attempt to have a special "bad format" error class in order to classify problems and only show the "real" errors, potentially multiple of them, which was a big improvement over the blanket "bad argument" message you used to get, and I am reluctantly considering for this issue.

Ideas:
- Can we impose or guarantee that the "string" passed to format classes **must** be a filename or URL?
- If we can get to a stage where the remaining parameters are either errors or in some class of (filename, URL, something else verifiable) - then things like non-existent files can be checked for early on in the process
- Otherwise, some flag on format classes e.g. `allow_nonstandard_scheme` that defaults to "False" so that if we want specific formatters to do something strange then we can allow "relaxed" conditions on checking the files, and trust the implementer to handle expected exceptions?

**Comment by ndevenish** [comment]
...and then you have formatters like `FormatHDF5` which [explicitly](https://github.com/cctbx/cctbx_project/blob/9589e2013d19ef59ad8b088f0568cf6cb9f9835d/dxtbx/format/FormatHDF5.py#L22-L23) trap `IOError` for - some reason?

**Comment by phyy-nx** [comment]
Speaking to your first point "Can we impose or guarantee that the "string" passed to format classes must be a filename or URL?"

Some insight.  A data source at LCLS is identified not by a file name but a string like this

exp=cxi78513:run=2

When @asmit3 and I were designing FormatXTC, we tried to get dials.import to just take that string on the command line and pass it on to FormatXTC as the filename, but we failed for all kinds of reasons, including issues suppressing phil parsing.  The idea was sound though, that we could pass a kind of URL that should have been directly understood by FormatXTC through dials.import and dxtbx.  In the end, we decided to have a 'locator' file which was a phil file on disc with datasource as a parameter in that file, and FormatXTC understands that phil format.  It works, but it means I can't run

dials.import exp=cxi78513:run=2

My point is that restricting format classes to file names or known url types limits design space.  XTC is a kind of streaming interface, and we have more of that coming....

**Comment by Anthchirp** [comment]
Sensible idea. But if you want to use URLs, why not stick to the [standard URL syntax](https://en.wikipedia.org/wiki/URL#Syntax)? Because that should be quite easy to detect, would not collide with PHIL (one hopes that doesn't allow ':' as part of names), and can then be treated separately by having some kind of handler mechanism...

**Comment by phyy-nx** [comment]
It could be fine.  Again, restricting dxtbx to filenames and URIs limits
design space, but perhaps one cannot have everything...

**Comment by ndevenish** [comment]
Right; I didn't know that form of argument existed but knew there weren't many constraints. Perhaps everything that isn't valid phil isn't being passed through at the moment, but to support this perhaps it *should*... 

Although in interests of sanity something even like `lcls://exp=cxi78513:run=2` would be infinitely preferable and much easier to parse - and like @Anthchirp suggested, would be relatively easy to parse out.

**Comment by Anthchirp** [comment]
We no longer use exceptions to identify formats. The `understand()` method is only allowed to return `True`/`False`.
