### ISSUE TITLE
Possibly a refinement question: can we assess level of similarity between unit cells from still images

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#345]
Given a set of indexed reflections and experiments from multiple images recorded in a raster scan, can we assess how similar they are i.e. perhaps some joint refinement with a restraint that they are all the same, the record / compute the deviation from this restraint. Particularly useful for cases where sample has orthorhombic symmetry or lower.

**Comment by dagewa** [comment]
You could do this, for example:

`dials.refine multi_experiments.json multi_indexed.pickle unit_cell.restraints.tie_to_group.sigmas=0.1,0.1,0.1,0.1,0.1,0.1`

which would restrain to the mean cell. This is a soft restraint - reduce the sigmas by an order of magnitude for a harder restraint. You'd have to calculate the mean cell again after the fact in order to compute the deviation. If this is slow (and it will be for large numbers of experiments) then probably prefer `restraint.phil` containing something like

```
refinement.parameterisation.crystal.unit_cell.restraints.tie_to_group{
  target=low_memory_mean
  sigmas=0.1,0.1,0.1,0.1,0.1,0.1
}
```

You can also use e.g.

```
refinement.parameterisation.crystal.unit_cell.restraints.tie_to_target{
  values=38.6,78.71,78.71,90,90,90
  sigmas=0.01,0.01,0.01,0.01,0.01,0.01
}
```

if you _know_ the cell you want to restrain to

**Comment by dagewa** [comment]
I think refinement with restraints satisfies the first requirement, then clustering as performed in dials.cosym probably satisfies the second ("record / compute...")?
