### ISSUE TITLE
All reflections failing in profile fitting

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#356]
With dials/latests, for some datasets, all reflections are failing in profile fitting, where as previously with dials/1.5 this wasn't the case. This is likely related to @jmp1985's recent changes to profile fitting.

The sigma_m is significantly different between the two dials versions:
```
$ grep "sigma m" /dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/002/DEFAULT/NATIVE/SWEEP1/integrate/tst_dials*/dials.integrate.log 
/dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/002/DEFAULT/NATIVE/SWEEP1/integrate/tst_dials/dials.integrate.log: sigma m: 0.118876 degrees
/dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/002/DEFAULT/NATIVE/SWEEP1/integrate/tst_dials_latest/dials.integrate.log: sigma m: 0.309126 degrees
```

With dials 1.5 release:
```
$ grep "Summary for experiment" /dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/002/DEFAULT/NATIVE/SWEEP1/integrate/tst_dials/dials.integrate.log -A 23
 Summary for experiment 0
 --------------------------------------------------------------
 Item                                  | Overall | Low   | High
 --------------------------------------------------------------
 dmin                                  | 1.95    | 5.29  | 1.95
 dmax                                  | 32.54   | 32.54 | 1.98
 number fully recorded                 | 1508    | 107   | 3
 number partially recorded             | 998     | 83    | 4
 number with invalid background pixels | 470     | 29    | 2
 number with invalid foreground pixels | 303     | 25    | 0
 number with overloaded pixels         | 0       | 0     | 0
 number in powder rings                | 0       | 0     | 0
 number processed with summation       | 2199    | 164   | 7
 number processed with profile fitting | 2177    | 163   | 5
 number failed in background modelling | 26      | 2     | 0
 number failed in summation            | 303     | 25    | 0
 number failed in profile fitting      | 325     | 26    | 2
 ibg                                   | 2.29    | 6.96  | 0.25
 i/sigi (summation)                    | 1.70    | 4.93  | 0.29
 i/sigi (profile fitting)              | 1.79    | 4.92  | 0.40
 cc prf                                | 0.08    | 0.13  | 0.05
 cc_pearson sum/prf                    | 0.99    | 1.00  | 0.44
 cc_spearman sum/prf                   | 0.61    | 0.67  | 0.40
 --------------------------------------------------------------
```
With dials/latest:
```
$ grep "Summary for experiment" /dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/002/DEFAULT/NATIVE/SWEEP1/integrate/tst_dials_latest/dials.integrate.log -A 23
 Summary for experiment 0
 ---------------------------------------------------------------
 Item                                  | Overall | Low   | High
 ---------------------------------------------------------------
 dmin                                  | 1.94    | 5.26  | 1.94
 dmax                                  | 32.54   | 32.54 | 1.97
 number fully recorded                 | 302     | 29    | 1
 number partially recorded             | 4114    | 299   | 6
 number with invalid background pixels | 823     | 49    | 3
 number with invalid foreground pixels | 530     | 39    | 0
 number with overloaded pixels         | 0       | 0     | 0
 number in powder rings                | 0       | 0     | 0
 number processed with summation       | 3880    | 288   | 7
 number processed with profile fitting | 0       | 0     | 0
 number failed in background modelling | 50      | 8     | 0
 number failed in summation            | 530     | 39    | 0
 number failed in profile fitting      | 4410    | 327   | 7
 ibg                                   | 2.28    | 7.00  | 0.24
 i/sigi (summation)                    | 1.29    | 4.05  | -0.04
 i/sigi (profile fitting)              | 0.00    | 0.00  | 0.00
 cc prf                                | 0.00    | 0.00  | 0.00
 cc_pearson sum/prf                    | 0.00    | 0.00  | 0.00
 cc_spearman sum/prf                   | 0.00    | 0.00  | 0.00
 ---------------------------------------------------------------
```

**Comment by rjgildea** [comment]
Run through xia2 thusly:
```
module load dials
xia2 image=/dls/i24/data/2017/nr16818-47/Josh/InSitu/CrystalQuickX/ProtK/NaI/ProtK_InSitu_NaI_47_66_1_0001.cbf
```

```
module load dials/latest
xia2 image=/dls/i24/data/2017/nr16818-47/Josh/InSitu/CrystalQuickX/ProtK/NaI/ProtK_InSitu_NaI_47_66_1_0001.cbf
```

**Comment by rjgildea** [comment]
For comparison, xds finds a similar mosiac spread to the sigma_m_algorithm=extended:
(001 = dials-basic, 002 = dials-extended, 003 = xds)
```
$ grep -i mosaic /dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/*/xia2.txt
/dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/001/xia2.txt:Mosaic spread: 0.119 < 0.119 < 0.119
/dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/001/xia2.txt:Mosaic spread: 0.105 < 0.105 < 0.105
/dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/002/xia2.txt:Mosaic spread: 0.309 < 0.309 < 0.309
/dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/003/xia2.txt:Mosaic spread: 0.316 < 0.316 < 0.316
/dls/i24/data/2017/nr16818-47/processing/rjgildea/ProtK/ProtK_InSitu_NaI_47_66_1/003/xia2.txt:Mosaic spread: 0.434 < 0.434 < 0.434
```

**Comment by rjgildea** [comment]
I should point out that these are relatively narrow wedges of data - 2.5 degree wedges of 0.1 degree images.

**Comment by jmp1985** [comment]
I'll have a closer look in a bit but I suspect that the difference in mosaicity is due to the added margin for prediction. The larger mosaicity means that fewer spots may be fully recorded and so forming the reference profiles might not work.


________________________________

**Comment by jmp1985** [comment]
I've had a look and I think this is the case. Also, it seems that there are a number of bad reflections in the strong spot list.

Processing reference reflections
 read 623 strong spots
 removing 212 unindexed reflections
 removing 184 reflections marked as centroid outliers
 using 227 indexed reflections
 found 396 junk reflections
 time taken: 0.000504971
 masked neighbouring pixels in 0 shoeboxes

Out of 623 spots, only 227 are used. In particular, I realised that dials.create_profile_model didn't filter centroid outliers and gave a much larger sigma_m estimate (~1deg rather than ~0.3deg with the filtering).

Just to reiterate, the reason that this is showing up now and not with old dials is that I have added a margin for prediction so that I match more of the strong spots than before.

James

________________________________
From: Parkhurst, James (DLSLtd,RAL,LSCI)
Sent: 31 May 2017 13:13
To: dials/dials; dials/dials
Cc: Assign
Subject: RE: [dials/dials] All reflections failing in profile fitting (#356)

I'll have a closer look in a bit but I suspect that the difference in mosaicity is due to the added margin for prediction. The larger mosaicity means that fewer spots may be fully recorded and so forming the reference profiles might not work.


________________________________

**Comment by jmp1985** [comment]
Just to clarify, as a result of the larger sigma_m estimate, and the fact that we have a narrow sweep, none of the strong spots are fully recorded and so no reference profiles are created since we only use fully recorded spots to create the reference profiles. Consequently, no profile fitting is done.

James

________________________________
From: Parkhurst, James (DLSLtd,RAL,LSCI)
Sent: 01 June 2017 09:42
To: dials/dials; dials/dials
Cc: Assign
Subject: RE: [dials/dials] All reflections failing in profile fitting (#356)

I've had a look and I think this is the case. Also, it seems that there are a number of bad reflections in the strong spot list.

Processing reference reflections
 read 623 strong spots
 removing 212 unindexed reflections
 removing 184 reflections marked as centroid outliers
 using 227 indexed reflections
 found 396 junk reflections
 time taken: 0.000504971
 masked neighbouring pixels in 0 shoeboxes

Out of 623 spots, only 227 are used. In particular, I realised that dials.create_profile_model didn't filter centroid outliers and gave a much larger sigma_m estimate (~1deg rather than ~0.3deg with the filtering).

Just to reiterate, the reason that this is showing up now and not with old dials is that I have added a margin for prediction so that I match more of the strong spots than before.

James

________________________________
From: Parkhurst, James (DLSLtd,RAL,LSCI)
Sent: 31 May 2017 13:13
To: dials/dials; dials/dials
Cc: Assign
Subject: RE: [dials/dials] All reflections failing in profile fitting (#356)

I'll have a closer look in a bit but I suspect that the difference in mosaicity is due to the added margin for prediction. The larger mosaicity means that fewer spots may be fully recorded and so forming the reference profiles might not work.


________________________________
