### ISSUE TITLE
Handle multiple lattices in more places

### ISSUE THREAD

**Issue by irisdyoung** [dials/dials#359]
There are a bunch of instances of `experiments[0]` and the like where it is unclear whether multiple lattices ought to be supported. Where there's some kind of `assert len(experiments) == 1`, it seems safe to assume the intended behavior is already present. I'm cataloguing here cases where it's not obvious to me whether it makes sense to look into adding support for multiple experiments. Opinions as to the relative priority of this? In any cases where we decide to support multiple experiments but to postpone that work, would it suffice to put an assert or Sorry in the way now so we can find them again?

Cases that probably should have asserts:

- XDS integrater

Ambiguous cases:

- xia2 dials refiner (computing total_phi_range)
- intersect_detector.py
- infer_s1_vectors.py
- xia2 dials integrater
- make_overlaps_plot.py
- integrate.py
- geometry_viewer.py
- estimate_resolution_limit.py
- compare_xds_dials.py
- simulation/reciprocal_space.py
- masker.py
- image_integrator.py
- indexer.py

Cases where I suggest multiple experiments ought to be supported:

- export_mmcif.py
- reindex.py
- filter_dead_time.py
- export.py
- check_strategy.py
- best_out.py
- align_crystal.py
- target_stills.py
- target.py
- stills_detector_metrology.py (there's a "FIXME" even)
- integrator_stills.py
- nave_parameters.py

**Comment by graeme-winter** [comment]
Supporting multiple lattices is very much on the to-do - an issue however is doing it *properly* - in some cases you list here this is relatively straightforward, in others it will be much harder. Would be useful to discuss sometime soon.

**Comment by dagewa** [comment]
In two cases (`target.py` and `target_stills.py`) the occurrence of `experiments[0]` is only in code that sets up a termination condition for refinement based on whether the RMSDs are within some fraction of the pixel size / image width. The pixel size and image width used for this is taken from the first experiment by convention. However, default behaviour is now not to exercise this code at all, because the dials.refine option `bin_size_fraction = 0.0` ensures that refinement runs to convergence or max iterations.

**Comment by dagewa** [comment]
Another case, `stills_detector_metrology.py`, is I think dead code. @phyy-nx does that seem right to you? I think it is only used by dev.dials.stills_detector_hybrid_refine. These days I think we use dials.refine directly for stills metrology, since the sparse LevMar engine made this tractable. Features like restraints and constraints may not be available to dev.dials.stills_detector_hybrid_refine. It might be time to retire that command and its non-shared dependencies completely.

**Comment by phyy-nx** [comment]
Agree! I'll create a separate issue for that. 

-Aaron

**Comment by rjgildea** [comment]
Several of the files you list I think are in the xia2 repository, so should be ignored. We have plans to add support for multiple lattices in xia2, but this is a separate issue, outside the scope of dials.

**Comment by rjgildea** [comment]
check_strategy.py can be ignored as it is just a development command that is hidden under the dev.dials scope.
align_crystal.py - this is used for calculating goniometer settings to align a crystal axis with e.g. the beam axis. It doesn't really make sense in the context of multiple lattices as you can only align one crystal at once!

**Comment by jbeilstenedmands** [comment]
As this is an old issue, if this is still relevant in parts, suggest we create more specific issues for individual cases.
