### ISSUE TITLE
move slow tests into dials_regression

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#374]
Can we move tests that are flagged as slow by libtbx.run_tests_parallel into dials.regression? Effects: we would run those tests less often, with a longer delay between commit and test, but still a minimum of once a day. Meanwhile all other tests would run noticeably faster.

Comments?
```
Warning: the following jobs took at least 180 seconds:
  libtbx.python "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_kapton_correction.py": 185.9s
  libtbx.python "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/algorithms/refinement/tst_sv_multi_panel_refinement.py": 195.1s
  libtbx.python "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_idials.py": 200.9s
  libtbx.python "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/tst_scan_varying_integration_bug.py": 207.4s
  libtbx.python "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/command_line/tst_integrate.py": 250.6s
  libtbx.python "/scratch/jenkins_slave/workspace/dials_tests/build_dials/modules/dials/test/algorithms/refinement/tst_multi_experiment_refinement.py": 370.6s
```

**Comment by graeme-winter** [comment]
tst_integrate needs to stay in there but we should have a shorter version of this which goes faster

**Comment by graeme-winter** [comment]
rest can go to _regression I would think

**Comment by graeme-winter** [comment]
@Anthchirp @ndevenish  between you want to work out how to make this happen? Am happy to come up with quicker data set to test integration with...

**Comment by ndevenish** [comment]
Probably shouldn't be too hard to move? I'm relatively concerted with the lack of differentiation between unit and regression/integration tests anyway [slow tests make it hard to run fast+often].

**Comment by ndevenish** [comment]
So I've looked at this briefly. I assume the Jenkins system is under heavy load/multiple simultaneous builds? Because I get significantly different results running on `nx-staff` (in principle fast CPU, slow filesystems), with these as my > 10s:
```
11.39 dials/test/model/data/tst_pixel_list.py
13.19 dials/test/algorithms/background/tst_modeller.py
16.69 dials/test/algorithms/image/connected_components/tst_connected_components.py
19.28 dials/test/command_line/tst_export_bitmaps.py
64.14 dials/test/algorithms/refinement/tst_multi_experiment_refinement.py
300s  Total
```
These mostly stand up under multiple runs (`tst_export_bitmaps` took 0.9s in another run, so I need to look into that some more). On my 2011 Macbook air (fast filesystem, slow CPU), without optimisation and with a load of debugging output still left in:
```
 14.77 dials/test/algorithms/image/filter/tst_median.py
 16.58 dials/test/algorithms/refinement/tst_scan_varying_prediction_parameters.py
 16.71 dials/test/model/data/tst_pixel_list.py
 27.14 dials/test/algorithms/background/tst_modeller.py
 36.28 dials/test/algorithms/image/connected_components/tst_connected_components.py
203.21 dials/test/algorithms/refinement/tst_multi_experiment_refinement.py
500s   Total
```

Multi-experiment refinement seems to be the most consistently long but I don't know what threshold it's worth moving stuff for.

Assuming that this is a mostly Jenkins problem and we want faster build/test cycles, @Anthchirp I know we discussed running tests through pytest, would it be more worth moving over to that and then being able to run some subset of tests on the tight commit->test loop?

**Comment by Anthchirp** [comment]
Yes, the build server has [varying load](http://jenkins.diamond.ac.uk:8080/view/DIALS/job/dials_tests/buildTimeTrend).
Moving dials to pytest probably not a short term option. @rjgildea suggested simply moving the tests by moving the relevant entries in ```run_tests.py``` between repositories.

**Comment by ndevenish** [comment]
Yes, but my point was it's *only* slow on the build server, and the timing of tests on the build server seems somewhat decoupled from the length of tests on developer's machines (see: integrate). It seems a mistake to optimise everybody's test running based on a single unrepresentative machine.

How about just `sed`-editing the test runner in the build process to explicitly skip those tests? Or perhaps an easier way to specify skipped tests?

Otherwise, how do we decide which tests to move?

**Comment by Anthchirp** [comment]
```sed```ing is not a good idea, because then nobody knows which tests are run where.
I don't care really how we do the selection though. My suggestion would be to start with a very simple criterion: Does the test require dials_regression? If yes, then it should be in dials_regression.

**Comment by ndevenish** [comment]
So, my apologies, this is where I notice:
- Some of the tests depend on `dials_regression`
- Some of the tests 'skip' if dials_regression isn't present
- Skipping apparently consists of printing "SKIP" to standard out and then exiting with 'success' code (0)
- The `libtbx.run_tests_parallel` counts skipped tests as passes, and importantly, **doesn't tell you this**

And therefore
- I have no idea at this point how Jenkins (and presumably whatever generates the written XML) classifies a test as skipped, but it's probably not picking up everything? A cursory search finds over 15 test scripts that "SKIP" without regression data. Perhaps they aren't all being run? Or the dials.tests includes regression data, but doesn't run the dials_regression tests?

This is probably worth a number of tickets all of their own to disentangle this. I can see at least:
- Tests that require `dials_regression` should be in dials_regression
- Skipped tests shouldn't show as successes
- Tests that change behaviour depending on availability of `dials_regression` should be split up
- Make an extra, non-regression integration test that runs much faster/with smaller available data
- Examine any remaining tests for build-system speed (this ticket)

**Comment by Anthchirp** [comment]
You are right, the libtbx testing framework does not natively support skipping tests. It is one of the missing features.
The skipping logic happens in libtbx/test_utils/parallel.py:231 and only affects the XML output, which is how Jenkins knows about this.

**Comment by ndevenish** [comment]
Could always unlink the `dials_regression` module for the "DIALS Tests" job to force the dependent tests to skip, though I'm not sure what the reverse of libtx.configure is. Then run both sets of tests in Regression Tests.

Perhaps it is simplest just to move the run_tests entries and check they work with relative paths. It should probably be an interim fix though with some further intentions, because it's only increases the WTF-cost and inter-module coupling of the code.

At least it'll get rid of the tests saying that they've passed when they haven't.

**Comment by phyy-nx** [comment]
I thought run_tests_parallel counted skipped tests as warnings?  The buildbot phenix build currently has 29 warnings because dials_regression isn't configured for that builder. 

-Aaron

**Comment by graeme-winter** [comment]
reverse of libtbx.configure is 

libtbx.configure —only `libtbx.list_modules | grep -v idontwantbx`

i.e. libtbx.configure —only only configures modules provided; provide list not including dials_regression would make what you want to happen, happen

**Comment by Anthchirp** [comment]
I would definitely like to move
```
dials.test.algorithms.background.tst_creator
dials.test.algorithms.integration.tst_profile_fitting_rs
dials.test.algorithms.integration.tst_summation
```
They require some simulated data in dials_regression to be present (which it isn't), and the simulated data creation was broken last time I checked (there may be a bug report for this), so we don't create this on-the-fly either.

**Comment by jmp1985** [comment]
Hi Markus, I'm not sure about the usefulness of these tests anyway. I guess they were an attempt to look at the statistics of background modelling, profile fitting and summation integration using simulated data.

**Comment by Anthchirp** [comment]
@jmp1985 So should these tests be removed rather than moved?

**Comment by jmp1985** [comment]
Hi Markus,

I'm going to move these to dials_scratch since I don't want to get rid of them but appreciate that they aren't very useful where they currently are.

James

**Comment by Anthchirp** [comment]
We do not run tests in dials_scratch, so that would be equivalent to removing them.

**Comment by Anthchirp** [comment]
Thank you (641d94dd60bf53ce50dd44569aad6eadaa00449a)
