### ISSUE TITLE
dials.index: index > 1 lattice but with almost identical UB

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#377]
```
------------------------------------
| Imageset | #indexed | #unindexed |
------------------------------------
| 0        | 53606    | 2268       |
------------------------------------
Finish searching for more lattices: 5587 unindexed reflections remaining.
Change of basis op: a,b,c


Rotation matrix to transform crystal 1 to crystal 2:


{{-0.546, -0.315, 0.776},
 {-0.307, -0.787, -0.535},
 {0.780, -0.530, 0.333}}


Rotation of 179.698 degrees
 
about axis (0.477, -0.326, 0.816)
```

**Comment by graeme-winter** [comment]
I suspect what has happened here is that the UB has changed some during the run, so you get a better model by splitting it in two...

**Comment by graeme-winter** [comment]
![newplot](https://user-images.githubusercontent.com/1241716/27419890-20338562-571b-11e7-897d-bd5c389906a4.png)

**Comment by graeme-winter** [comment]
Quite possibly the second lattice is a split fragment which only becomes visible for part of the set

**Comment by rjgildea** [comment]
This is likely the expected behaviour with split spots that are from the same underlying crystal. It may well be less of an issue with the dipsersion_extended spot-finding algorithm if that reduces the number of split spots. Setting the known space group should mean that lattices that are related by a known symmetry operator to the first lattice will be ignored.
