### ISSUE TITLE
Minimizer: explore SVD of Jacobian matrix minimisation for scaling

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#400]
@dagewa to furnish this ticket with *content*

**Comment by dagewa** [comment]
What Aimless does is described in [the paper](http://www.ncbi.nlm.nih.gov/pubmed/16369096) as 'singular value decomposition', but it is not what is meant here. The Aimless method does eigenvalue filtering on the normal matrix (which we also want in #401). What we mean here is to do SVD on the Jacobian and never form the normal matrix. This is computationally expensive but numerically stable (see [Wikipedia](https://en.wikipedia.org/wiki/Linear_least_squares_(mathematics)#Orthogonal_decomposition_methods)). As well as being robust, the SVD approach provides more information about the sensitivity of the solution to perturbations in the data (Nocedal & Wright).

Most importantly though, the SVD approach can be used to solve rank deficient and underdetermined problems, guaranteeing the minimum norm solution out of the infinite number of possible least squares solutions. This is relevant to scaling because what we are interested in is the relative scale, but fixing one scale parameter is problematic (see [Fox & Holmes](http://scripts.iucr.org/cgi-bin/paper?S0365110X66002007))
