### ISSUE TITLE
spotfinding should output imageset_id instead of id

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#408]
Currently spotfinding outputs the `id` column (corresponding to "imageset id"), which is then copied to the `imageset_id` in indexing (and various other places) whereas after indexing the `id` column corresponds to "experiment id", not "imageset id". It would be more straightforward if spotfinding output the `imageset_id` column in the first place, rather than confusing the definition of the `id` column (which can lead to subtle bugs in places).

**Comment by jmp1985** [comment]
I'm not sure an additional id should be necessary. After indexing, if we have an id that refers to an experiment then this will also necessarily refer to an imageset. So after indexing an imageset_id will be redundant.

**Comment by rjgildea** [comment]
dials.index already converts the 'id' column to 'imageset_id' on input, and I believe this column then gets carried all the way through DIALS processing. It would be simplest, and less confusing, if dials.find_spots would output 'imageset_id' in the first place.

**Comment by jmp1985** [comment]
I think it's fine to propagate columns in the reflection table even if they are only used in one program so I don't mind the imageset_id being carried all the way through the processing. Although, its worth noting that while it exists in the reflection table for predicted reflections in integration, it will probably have a value of 0 for predicted reflections that were not found as strong spots.

In all cases, the id column essentially refers to images and a set of models so I don't find the use of it in spot finding confusing. Perhaps the confusion arises due to the use of different data structures - we briefly spoke about retiring the datablock class and just using experiment list throughout so maybe this would make things less confusing here.

However, I don't feel particularly religious about this so if everyone else is banging their heads about it, I might consider changing the behaviour.

**Comment by dagewa** [comment]
Seems this got nowhere. I'm closing, but please reopen if required.
