### ISSUE TITLE
Error bars for scan-varying unit cells

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#414]
![newplot 1](https://user-images.githubusercontent.com/1241716/28054311-4c4f2750-660c-11e7-9ab0-1282c0a0c915.png)

Does this look right?

Was some radiation damage over the second half of the set though not catastrophic, but the variation is decidedly non sinusoidal...

**Comment by graeme-winter** [comment]
[could this be a sign of a dodgy gonio?]

**Comment by graeme-winter** [comment]
![newplot 2](https://user-images.githubusercontent.com/1241716/28057627-7b36dade-6618-11e7-8aaa-98e535f0a73a.png)

**Comment by dagewa** [comment]
Looks very reasonable to me. The cell parameter variation is pretty small, the graphs are essentially zooming in on the noise.

**Comment by rjgildea** [comment]
Less than 0.2% variation in cell lengths, not really problematic?

**Comment by graeme-winter** [comment]
Not problematic per se; odd; got me wondering you see... no problem though

**Comment by graeme-winter** [comment]
(wonder: could we assign some kind of "significance" to these i.e. almost error bars on this plot?)

**Comment by rjgildea** [comment]
The crystal model should have the associated sigmas for the parameters from refinement?

**Comment by dagewa** [comment]
The sigmas are set after static refinement but not scan-varying. Nothing in principle stopping calculation of scan-varying sigmas, but it implies quite a lot larger .json file (81 element covariance matrix stored per scan point)

**Comment by graeme-winter** [comment]
@dagewa could we make that an option? May be quite instructive, if huge.

**Comment by graeme-winter** [comment]
Guess that counts as a feature request, at least for exploration, so reopening...

**Comment by dagewa** [comment]
Rather than messing with the crystal model, just to see what to expect I dumped the B covariance matrices for scan-varying refinement of the I04 BAG training data to a pickle file then hacked this into `dials.plot_scan_varying_crystal`
![unit_cell](https://user-images.githubusercontent.com/11502083/28723446-abafd12c-73ae-11e7-8138-7db06973106e.png)
Interesting, so the estimated ESDs for scan-varying refinement are _much_ larger than the static ESDs. This makes some sense I suppose, as the unit cell at some scan-point is determined by much less data than the overall static cell. Still not entirely sure I trust the result though. It will be worth looking through the calculations again.

**Comment by graeme-winter** [comment]
Crystallographic wise this plot makes sense. As a,b become better determined c becomes less so. Would like to reproduce this with other data. I can has instructions?

**Comment by dagewa** [comment]
It's a dirty horrible hack, so here's a patch
[sv-cell-error.patch.zip](https://github.com/dials/dials/files/1183477/sv-cell-error.patch.zip)

**Comment by dagewa** [comment]
...do scan-varying refinement as normal. A file `ScanVaryingCrystalUnitCellParameterisation-state_uncertainties.pickle` will be created. Run `dials.plot_scan_varying_crystal refined_experiments.json` and this will be read and the error bars added.
