### ISSUE TITLE
Outlier rejection in stills indexer

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#424]
I often observe Sauter, Poon (2010) in `stills_indexer.py` rejects lots of innocent reflections.

The problem in the algorithm is that it assumes a single spot RMSD for all panels and all resolutions. In reality, the metrology of outer panels tends to be less accurate, and high resolution spots are more strongly affected by radial streaking due to parallax and bandwidth. Thus, high resolution spots are more likely to be rejected than low resolution spots. Once a spot is flagged as an outlier in the indexer, it will never be used, for example, in the joint refinement. Thus, panels with poor metrology receive less surviving spots and they will not be refined properly. Another problem is that it leads to a poor mosaicity model and under-prediction.

However, completely disabling the outlier rejection led to unstable refinement. Do you have any suggestions?

# Example
This is Proteinase K collected at 10 keV (similar to CXIDB 48).
Actually, this is not a good example, as there are many spots from the beginning.

## strong.pickle
![image](https://user-images.githubusercontent.com/1611483/28564987-c3e8d130-7165-11e7-9264-cd08d1ed409a.png)

## indexed.pickle
![image](https://user-images.githubusercontent.com/1611483/28565015-d54c3b74-7165-11e7-8d01-0f15c5a3fd36.png)

## integrated.pickle
![image](https://user-images.githubusercontent.com/1611483/28565070-0c858dca-7166-11e7-91f6-2ecdb1117741.png)

NOTE: pixels at edges of each panel are actually masked (not shown).

**Comment by biochem-fan** [comment]
This image also shows the effects of bandpass and parallax.

The bandpass is about 1.5 % of 10 keV = 150 eV. The sensor thickness is 300 um.
The incident angle is about 45 deg at the edges.

The spot finder sometimes splits radial streaks into multiple spots.
![image](https://user-images.githubusercontent.com/1611483/28565828-4f04dc9e-7168-11e7-8276-690f9bd4aede.png)
(rotated 90 deg)

**Comment by phyy-nx** [comment]
Hi, the real issue here is that the stills indexer always does a round of
Sauter Poon outlier rejection algorithm while refining candidate basis
sets.  Specifically, after refinement of a candidate, we re-run outlier
rejection using Sauter Poon.  It sounds like you need a way to disable this
behavior, so that you can
specify refinement.reflections.outlier.algorithm=None and have it be
respected by the stills indexer.  I agree.  That makes a lot of sense for
metrology refinement.  But normal day-to-day processing should still use
Sauter Poon.  Among other reasons that it's very useful for rejecting spots
indexed from different lattices (as the second author of the 2010 paper was
just describing to me :)

As to the spotfinder splitting radially distorted spots (probably from SASE
spectra), that's a different issue.  Is there a parameter to enforce spots
be a minimum certain distance from each other?  That could cause undesired
behavior in the multiple lattice case.

**Comment by biochem-fan** [comment]
Hi, thanks for comments.

>  It sounds like you need a way to disable this behavior, so that you can specify refinement.reflections.outlier.algorithm=None and have it be respected by the stills indexer.

Simply commenting out Sauter-Poon was not very helpful; refinement became unstable. I will try disabling Sauter-Poon and using MCD or Tukey instead as in standard refinement.

> But normal day-to-day processing should still use Sauter Poon. Among other reasons that it's very useful for rejecting spots indexed from different lattices

I am not sure... Even when the metrology is good, it is still biased to reject more high resolution spots than low resolution spots. The effect of parallax can be modelled, but the effect of bandwidth cannot, so centroid positions of high resolution spots have higher variances. This is evident from the transverse and radial RMSD plots.

Of course, having many choices is a nice thing. Probably one algorithm does not fit all datasets.

> Is there a parameter to enforce spots be a minimum certain distance from each other?

Making `min_spot_size` larger helped a bit. I don't think DIALS has the `min_distance` criterion.

**Comment by phyy-nx** [comment]
Hi Takanori, systematic mis-prediction of high resolution spots due to
bandpass and mosaicity is problem.  It makes sense that this will
complicate metrology refinement.  I don't have a solution to this worked up
yet.  Stay tuned.

I look forward to hearing how the MCD and Tukey tests you are trying go.
In the meantime, I'll implement disabling the additional Sauter/Poon
outlier rejection in the stills indexer via a phil parameter as soon as I
can.

**Comment by phyy-nx** [comment]
Hi Takanori, I added the parameter indexing.stills.candidate_outlier_rejection=True.  Set it to false to disable the Sauter/Poon outlier rejection in the stills processor.

I've closed the issue since better integrating radially streaked spots and more accurately predicting spots at high resolution are longer term goals.

As an aside, if you use integration.debug.output=True and integration.debug.separate_files=False, you can run the dials image viewer with the integrated.pickle files and see the integration masks (show with 'spot all pixels').  (These options are memory intensive when processing sweeps, but for stills it's fine).  I'd be curious how well the masks fit your radially streaked spots.

**Comment by biochem-fan** [comment]
Thanks. I disabled Sauter-Poon and tried (1) no outlier rejection at all, (2) MCD and (3) Tukey.
I had to comment out some assertions and forcing-to-'null' codes, though.

The results were inconclusive. Prediction improved in some images, not in others. It seems that
outlier rejection in Nave parameter estimation is the next issue.

For integration masks, I opened a new issue #426.
