### ISSUE TITLE
Integration masks for stills

### ISSUE THREAD

**Issue by biochem-fan** [dials/dials#426]
Continuing from #424, integration masks for XFEL images with bandwidth effect (radial streaking) are not optimal.

![image](https://user-images.githubusercontent.com/1611483/28724342-a26c5720-73f4-11e7-830b-33988e36d61f.png)
(rotated by 90 deg)

As the above image shows, the mask misses some signals although centroids look OK.

Properly modeling this effect might be tough, but (1) an option to enlarge empirical masks by specified pixels and (2) an option to fix the integration radius (as in CrystFEL's --int-radius option) might be useful.

**Comment by biochem-fan** [comment]
After hacking `algorithms/shoebox/mask_empirical.h` and `algorithms/integration/integrator_stills.py` to implement (1), I realized that `dials.stills_process` does NOT use these codes. Instead, the still integrator uses the `MaskCalculator2D` in the `gaussian_rs` profile model.

@phyy-nx, how can I use empirical masks implemented in  `algorithms/integration/integrator_stills.py`? Are they not finished?

**Comment by phyy-nx** [comment]
Hi Takanori, I believe the DIALS interfaces changed and this code was left
behind.  I didn't go back and hook it up again because MaskCalculator2D
seemed to be working fine for most cases.  It may be possible to restore
this functionality, which could mostly solve the radial streaking problem.

For those unaware, the empirical masker creates an integration mask for a
given reflection by taking the union of the foreground pixels of the 10
nearest indexed strong spots as determined by spotfinding.  The nice thing
about the empirical masker is that it accounts for local variation in spot
shape, especially in the radial streaking case.  While it's not perfect (a
huge low resolution reflection or a mis-indexed blob of ice can cause
nearby integration masks to be huge), it's probably worth trying.

**Comment by biochem-fan** [comment]
I see. Could you (or @jmp1985) please restore this code path when you have time?
I don't know these interfaces and the developer tutorial does not say much.

**Comment by phyy-nx** [comment]
I am quite interested in restoring these!  When I get a chance I'll look at
it.  It's good to leave this issue open until then.

**Comment by biochem-fan** [comment]
Thanks. I am looking forward to it.
