### ISSUE TITLE
DIALS cookbook

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#463]
Since we will never have full documentation, some recipes would be useful i.e. documented and annotated "how to" guides, for example derived from refactoring in #462

**Comment by jbeilstenedmands** [comment]
I was thinking that I could be quite involved with this, given that I'm coming across lots of these "how to" issues myself as I'm learning the ins and outs of dials.

**Comment by graeme-winter** [comment]
Be my guest 😄

**Comment by graeme-winter** [comment]
Have taken liberty of making a start in wiki:

https://github.com/dials/dials/wiki/DIALS-Cookbook

**Comment by dagewa** [comment]
This was a nice idea, but hardly got started and already suffers from code rot. For example, the [boilerplate](https://github.com/dials/dials/wiki/Boilerplate-%28or-the-standard-framework-of-a-DIALS-program%29) entry is out-of-date because (at least) it is not black format.

It might be better to add how to jiffies as tests?

**Comment by dagewa** [comment]
Deleted
