### ISSUE TITLE
dials.find_spots: default squares the panel gain for spot-finding

### ISSUE THREAD

**Issue by dagewa** [dials/dials#469]
Previously we ascertained that the `xds.gain` parameter to dials.find_spots acts as a multiplier for the panel's gain. I've just been testing that, and indeed this seems to be the case. For a CCD dataset (xia2_regression/test_data/mad_example/12287_1_E1_0*.img) with gain edited in datablock.json, all these jobs seem to be equivalent
```
dials.find_spots datablock_gain_1.0.json xds.gain=2.4 nproc=8
dials.find_spots datablock_gain_2.4.json xds.gain=1.0 nproc=8
dials.find_spots datablock_gain_2.0.json xds.gain=1.2 nproc=8
dials.find_spots datablock_gain_1.2.json xds.gain=2.0 nproc=8
```
However, these jobs are _not_ the same
```
dials.find_spots datablock_gain_2.4.json xds.gain=1.0 nproc=8
dials.find_spots datablock_gain_2.4.json nproc=8
```
It turns out that when the xds.gain is not set, it is taken from the panel. See [spot_finding/factory.py](https://github.com/dials/dials/blob/master/algorithms/spot_finding/factory.py#L558).

But isn't that weird? Given that `xds.gain` is a multiplier for the panel gain, the default behaviour seems to be to square the panel gain for spot-finding.

**Comment by jmp1985** [comment]
I agree that this is a bit weird. Especially as the data processed is from get_corrected_data  so if the xds.gain is set then that is applied on top. Perhaps the xds.gain parameter should be removed and the gain should just be used as a property of the panel.


________________________________

**Comment by dagewa** [comment]
Hi James,

I think the short term fix is to set `xds.gain=1.0` as default, not `None`. That way when it is applied as a multiplier for the panel gain it does nothing. However, that change will affect spotfinding for CCDs etc. and thus change xia2 regression test results.

Longer term, retiring `xds.gain` sounds like a good idea as having multiple different ways to specify the gain is confusing (see also #385).

At the moment I am investigating why spot finding from XDS gives different results from DIALS when the core algorithms should be very similar. This squaring the gain behaviour is one aspect of that, but I don't think it is the only relevant issue. I'll collect some results, then I think when you're back it will be good to meet to discuss what I find. What comes of this may affect https://github.com/cctbx/cctbx_project/issues/51.

Cheers
David

**Comment by jmp1985** [comment]
One consideration is that if we do the spot finding on the image returned by get_corrected_data which has the gain applied as:

corrected = raw / gain

And apply D > 1 + Ns * sqrt(2/(N-1))

This is only the same as doing the spot finding on the raw data with D > G * (1 + Ns * sqrt(2/N-1)) if the gain is uniform across the detector. If the gain varies in the local region of the spot then the two will give different results. 

So the question is, should we apply the gain in the "get_corrected_data" function and apply the spot finding on that image. Or should we apply the gain in the spot finding algorithm as described in the paper and do the spot finding on the raw data?

**Comment by graeme-winter** [comment]
This reminds me that the definition of "raw" data is rather poor - and was something we were going to revisit - @phyy-nx ring any bells?

**Comment by dagewa** [comment]
I suppose you could argue that spot-finding should be done on the image that best represents the actual diffraction pattern. You would want to remove any image pedestal and correct for any geometric distortions that might in principle be present in any case, whether or not you divide through by the gain. So that sounds like given the choice between get_raw_data and get_corrected_data you'd want to use get_corrected_data.

In that case, _as long as the gain was actually correct_ then doing D > 1 + Ns * sqrt(2/(N-1)) in units of X-ray photons should be the Right Thing... yes?

**Comment by jmp1985** [comment]
OK - so that sounds reasonable. I'm going to change the behaviour such that we apply the gain to the image and do the spot finding there (this is already done but I need to remove the additional application of the gain in the spot finding algorithm). 

I think the reason for the weird behaviour is that in the past, we used the raw data and and you could set the gain used in the algorithm from either the parameter or from the gain in the panel. However, at some point we changed to use the corrected_data and this was never fixed. 

I've removed the code that uses the panel gain in the algorithm if nothing is set. For the moment, I'm going to use the gain set in the algorithm parameters just in the algorithm. This means that the behaviour will be as follows:

The gain set in the detector or as a lookup map will be used to generate the corrected_data array. It will not also be set in the algorithm so we won't be squaring the gain any more. The gain set in the algorithm will then essentially act as a multiplier and will be used in the algorithm. 

An alternative would be to use the gain parameter to override the gain in the datablock. However, an argument against this would be that we tend to use the spot finder gain in unphysical ways so maybe we shouldn't be setting this in  the detector - you can override the expected gain for the detector in dials.import.

**Comment by dagewa** [comment]
I think that all sounds good, thanks.

**Comment by jmp1985** [comment]
OK so this is now committed
