### ISSUE TITLE
Discussion topic: experiment.id != (0,1, ..., (n-1))

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#507]
Currently when indexing > 1 sweep we have 

dials.index db1 refl1 db2 refl2 

and the _order_ defines the experiment id - this is obviously fragile. Therefore, the concept of having the dataset id or experiment id be a unique ID rather than an integer counting from 0 would help to reduce the chance of this.

Proposal:

datablock.id is created which is a unique identifier (perhaps random number, better a hash derived from pixels) which is then used as the id column in the derived strong pickle. Then, this can be used to reliably match up reflections with source

Same applies to experiments...

Thoughts?

**Comment by phyy-nx** [comment]
Another use case to consider is images referenced by timestamp, such as we
get from xfel data.  I find I can easily lose track of which shot an
experiment id came from after a few dials.combine_experiments, and an
arbitrary hash wouldn't help me find my way back.  However, if there were a
hash in string form that was application specific, that would be very
helpful as I could use my timestamp as the hash.

**Comment by graeme-winter** [comment]
Reflection table has lookup in dictionary => points to same value as experiment.id

**Comment by graeme-winter** [comment]
@jmp1985 says sounds sensible

**Comment by graeme-winter** [comment]
Needs to be on serialise / de-serialise that this is used.... mostly working algorithms should not be changed as the experiment id (working wise) should still be a small integer

**Comment by graeme-winter** [comment]
@nksauter @phyy-nx you have opinions about this, happy for us to go ahead? Really need this for multi-experiment handling in scaling (and @jmp1985 going to start looking at this real soon)

**Comment by dagewa** [comment]
Just a note to say that I am sure that refinement code will need changes following this. The assumption that the order of experiments determines the experiment id is made in a few places, I think. Current tests won't pick this up unless that assumption is violated in the tests.

**Comment by phyy-nx** [comment]
I also have made the assumption that the order of the experiments determines the experiment ID in many places. I wouldn’t want to get rid of that assumption. I would want however to add a hash or string that would help us always be able to connect an experiment with its source.

If we do feel it’s important to break this assumption, I would need time to look for where it’s relied on in the XFEL sources. It would be any loop like this (and there are many loops like this in the source code).

for exp_id, experiment in enumerate(experiments):
  refls = reflections.select(reflections[‘id’] = exp_id)

-Aaron

**Comment by jmp1985** [comment]
In the first instance, I propose implementing this and only using as a verification tool. So we can keep assuming that the order of experiments determine their integer ID. I.e. when experiments and reflections are loaded into a dials program, ensure that the order or the experiments matches the order of identifiers in the reflection table. 

I.e. if we load experiments with the following identifiers in this order:

ID 0 -> sausage
ID 1 -> eggs
ID 2 -> bacon
ID 3 -> toast

And at the same time load a reflection table which has a mapping of integer ids as:

0 : sausage
1 : eggs
2 : bacon
3 : toast

Then we proceed as normal. If however, the order expressed in the reflection table is (for example):

0 : bacon
1 : eggs
2 : sausage
3 : toast

I.e. it doesn't match then we throw an exception. This then keeps the assumption of order of experiments determining the experiment ID. Then in the future we might decide to do more funky things to reorder things based on the identifiers given as input.

**Comment by phyy-nx** [comment]
This is fine. A note that when reflection tables get big, this could be time consuming.    If the validation were done in C++ it probably wouldn’t be an issue.

-Aaron

**Comment by jmp1985** [comment]
@phyy-nx My proposed implementation is to keep integer reflection ids in the reflection table. I'm then going to add separate dictionary (or probably a map in c++) which maps an integer to a string. Each experiment will then have a string identifier.

The verification would then involve, checking that experiment ids in the reflection table are within the range given in the reflection table identifier dictionary. And then checking that the order of experiments matches the order of strings in the dictionary. I'm hoping that this won't incur too much overhead but I'll do it in C++ as you suggest to make sure it's as fast as possible!

**Comment by graeme-winter** [comment]
Assuming that this now exists, would be good to have this unique identifier made early in the process - ideally on import. Suspect that sausage etc. could be hard to wrangle carefully, but something like ab56b4d92b40713acc5af89985d4b786 could be easier to generate. 

Re: #613 if dials.import giveth experiments, could this kind of identifier be made e.g. from a hash of the header info or something. This need another ticket?

**Comment by jmp1985** [comment]
Generating a unique string in import either out of thin air or based on some property of the images should be easy. But during indexing with multiple lattices we will then need to regenerate experiment ids (or augment the experiment id perhaps with a hash made from the unit cell info perhaps?).

**Comment by graeme-winter** [comment]
Easier - hash the hash you start with with experiment id, to get a new hash 🙂

**Comment by jmp1985** [comment]
That would also work!

**Comment by graeme-winter** [comment]
Bringing this bad boy back to life...

If we assert that the identifier is a `string` only i.e. we do not constrain it further than that, then we can make dials.import offer options as to what to use e.g.

```
dials.import (images) identifier=12345
dials.import (images) identifier_type=uuid
dials.import (images) identifier_type=image_hash
```

i.e. we can push this to be an _option_ then work with what we are given - provided that we have a sensible default e.g. UUID we can then have alternatives which something smart like xia2 could use...

**Comment by asmit3** [comment]
Is the idea here that the identifier be assigned during dials.import or when the file is read in by the format class ? When I run the following 2 programs using the branches in cctbx/dxtbx#39 and dials/dials#819, I get different output for the identifier

**Case 1: dials.import**
```
dials.import mfx_data.loc

(myEnv) [asmit@psanagpu106 stills_process_try]$ head imported_experiments.json -n 10
{
  "__id__": "ExperimentList", 
  "experiment": [
    {
      "__id__": "Experiment", 
      "identifier": "", 
      "beam": 0, 
      "detector": 0, 
      "imageset": 0

```
**Case 2: dials.stills_process**
When I run stills_process.py,  the experiment identifier is preserved from start to finish

```
dials.stills_process mfx_data.loc

(myEnv) [asmit@psanagpu106 stills_process_try]$ head idx-mfx_data_00000_integrated_experiments.json 
{
  "__id__": "ExperimentList", 
  "experiment": [
    {
      "__id__": "Experiment", 
      "identifier": "2016-12-13T21:10Z19.804-00", 
      "beam": 0, 
      "detector": 0, 
      "crystal": 0, 
      "profile": 0, 

```
It seems there is a re-assignment of the ExperimentList within dials.import which leads to case 1 not preserving the identifier. Is it intended or a known thing ?

**Comment by jbeilstenedmands** [comment]
Hi Asmit,
I'm looking into this at the moment. You are correct, dials.import seems to do a few rounds of reading the data and creating the experiment list. I didn't write the code so I'm not sure, but I assume it's done this way for a reason. My initial attempts to tackling this is just to have a separate function `set_identifiers` which is called each time an experiment list is created to catch all cases. For stills process, does the identifier need to be set when reading the format class? If not, then I think a function  like this could just be called when importing in either dials_import or stills_process:
```
def set_identifiers(experiments, params):
    if params.input.identifiers:
        if not len(experiments) == len(params.input.identifiers):
            raise ValueError("Mismatched number of experiments and user-input identifiers")
        for i, exp in enumerate(experiments):
            exp.identifier = params.input.identifiers[i]
    elif params.input.identifier_type != 'none':
        for exp in experiments:
            exp.identifier = make_identifier(exp, params.input.identifier_type)
    return experiments

def make_identifier(experiment, id_type='uuid'):
    assert id_type in ['uuid', 'image_identifier']
    if id_type == 'uuid':
        return ''
    elif id_type == 'image_identifier':
        return experiment.imageset.get_image_identifier(0)
```

**Comment by asmit3** [comment]
Hi James,

If the identifier is set everytime the ExperimentList is constructed, that should work. Essentially that is what is being done in

https://github.com/cctbx/dxtbx/blob/605e1d4bf14dcf32fd7fd4addf66b8bee11b0213/model/experiment_list.py#L729-L730

I am assuming here for formatXTC that the imageset will get the image_identifier information from the format class.

**Comment by phyy-nx** [comment]
All, I'm swamped by beamtimes but I'm writing up a proposal that I hope will satisfy all parties.  Please let's not resolve this issue, cctbx/dxtbx#39 or #819 until I've posted it?  Thanks!

**Comment by graeme-winter** [comment]
@phyy-nx sure, though I look now and this topic was raised ~ 16 mo ago! 😱clearly not urgent-urgent then, but would be good to get this resolved.

IMHO a string which is determined at experiment-creation time would be neatest, then this can come from wherever...

**Comment by graeme-winter** [comment]
@rjgildea @ndevenish @dagewa @jmp1985 @benjaminhwilliams and probably others - would be worth hunting through for assumptions about experiment identifiers... though in algorithms they will be integers and _should_ not function differently...? Maybe output will need to dereference the identifier name from (whatever the conclusion to this ticket is)

**Comment by phyy-nx** [comment]
Hm... re-reading all the threads on identifiers I see I may have been hasty. I see two possible approaches are being discussed.

1.	Identifiers can be anything, human readable or not.  They could be generated automatically (uuids/hashes), they could be specified using human specific labels, or they can be generated by the format classes themselves.
2.	Identifiers are only uuids/hashes.  They are generated using a standard approach that we work out here.  If we need additional information (such as timestamps), then we create additional fields on the experiment object, or possibly the experimental models.

Problems with 1:
-	How to ‘duplicate’ an experiment?  For example, during indexing with multiple lattices, how are the multiple experiments tagged?  #819 appends the lattice number, but what if the experiment is further modified?  Not something I really considered when @asmit3 and I were talking about that pull request.

Problems with 2:
- @jbeilstenedmands has already been using custom strings as identifiers so that would need to be re-worked.  Further, users would not be able to specify human readable names for experiments

For 2, adding fields like timestamp directly to the experiment starts to clutter the experiment object and starts defeating its purpose, as a repository for models, not a repository for information.  Adding fields to the experimental models, like timestamp to the imageset, seems more reasonable.

For reference, the current fields on experiment are beam, crystal, detector, goniometer, identifier, imageset, profile, scaling_model, and scan.  

I'm leaning towards 1 as I value the flexibility, but I'd like to hear more comments.

**Comment by dagewa** [comment]
> @rjgildea @ndevenish @dagewa @jmp1985 @benjaminhwilliams and probably others - would be worth hunting through for assumptions about experiment identifiers... though in algorithms they will be integers and _should_ not function differently...? Maybe output will need to dereference the identifier name from (whatever the conclusion to this ticket is)

I've not been following this discussion closely. My only comment is that refinement uses this kind of logic in at least 24 separate places:
https://github.com/dials/dials/blob/0c5a31b48b7888821bdd8efa6fa1979447277301/algorithms/refinement/prediction/managed_predictors.py#L86-L89

Also there is this kind of looping construct used in many places:
https://github.com/dials/dials/blob/0c5a31b48b7888821bdd8efa6fa1979447277301/algorithms/refinement/parameterisation/configure.py#L390-L393

From the discussion it sounds as though the proposals are designed so that this continues to work. I would be happy if that is the case. Refinement doesn't change the order or length of experiment lists so there shouldn't be any difficulties arising from that. Once the dust has settled on experiment identifiers, the refinement code could benefit from it by creating a more robust way to specify constraints and restraints for experiments.

**Comment by ndevenish** [comment]
Would adding an explicit title/note/comment field to experiments, that can contain anything and is not designed to be meaningful, solve the problem that you are trying to solve here?

**Comment by phyy-nx** [comment]
@ndevenish that is essentially option 2, e.g. use uuids/hashes for experiment identifiers and add any metadata we are missing as fields on either the experiment or other experimental models.  It affects @jbeilstenedmands's work since he'd have to switch to hashes and doesn't give us flexibility in what we can use for identifiers.  Note I'm not ascribing value here, just trying to articulate the issues :)

Also note I'm not trying to just solve the problem @asmit3 and I have with XTC, I'm trying to solve the general problem of what experiment identifiers are.

@dagewa I'm distinguishing identifiers (strings) from ids (integers).  I'd agree that the code you have above woudn't be affected.

**Comment by jbeilstenedmands** [comment]
Regarding my current use of the identifiers, I'm happy for this to be affected. My thoughts were that when the experiment Id (string) is some hash/timestamp etc, then for user input I would switch to use the 'id' (integer) from the reflection table instead, which would be a low integer value and so keep a similar functionality to present.
