### ISSUE TITLE
image_viewer libjpeg.so.62 error on 'recent' distributions

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#523]
When installing the release package. This is because on e.g. Linux mint 17.3 (Dec 2015) only libjpeg8 is installed by default.

```
Traceback (most recent call last):
  File "/opt/dials/dials-v1-9-0/build/../modules/dials/command_line/image_viewer.py", line 150, in <module>
    import wx # It is unclear why, but it is crucial that wx
  File "/opt/dials/dials-v1-9-0/base/lib/python2.7/site-packages/wx-3.0-gtk2/wx/__init__.py", line 45, in <module>
    from wx._core import *
  File "/opt/dials/dials-v1-9-0/base/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 4, in <module>
    import _core_
ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory
```

Same issue on the current ubuntu LTS 16.04 (April 2016) - and almost certainly the new LTS coming out in April (17.04). This is a different issue from https://github.com/cctbx/cctbx_project/issues/85 which is explicitly related to building.

I'm guessing we don't have many non-power users on "recent" installations that this hasn't come up more than once-or-twice.

**Comment by phyy-nx** [comment]
The configure scripts for these third party dependencies are too clever
sometimes and link against whatever they can find.  cci-vm-X machines, on
which buildbot does its nightlies, have minimal OS installations with a
minimum amount of development libraries to avoid issues like this.  Here,
specifically, if wxPython cannot find libjpeg, it uses its own.

Nick, can you send the base_tmp/wxPython_install_log file?  Or look at this
section (taken from cci-vm-7's nightly build of phenix):

Which libraries should wxWidgets use?
                                       STL                no
                                       jpeg               builtin
                                       png                sys
                                       regex              builtin
                                       tiff               sys
                                       zlib               sys
                                       expat              sys
                                       libmspack          no
                                       sdl                no

We see that the jpeg library picked is the builtin version.  What do you
see?  If you see sys listed for jpeg, a possible solution would be to
remove the jpeg development headers from your build machine so that the
binary bundles compile and link against the built in jpeg library.

-Aaron


On Thu, Mar 22, 2018 at 5:22 AM, Nicholas Devenish <notifications@github.com

**Comment by ndevenish** [comment]
So, looking at this again, because we've had a load of people using new ubuntu laptops here. Unfortunately removing libjpeg isn't possible on our build machine and we don't have e.g. a containerised infrastructure that would solve the problem neatly.

I can see a couple of possible solutions, but aren't sure which would be preferable to you:
- Always building wxWidgets with `--with-libjpeg=builtin` (this would prevent using e.g. newer libs when available)
- Having e.g. an `WXWIDGETS_CONFIGURE_FLAGS` environment variable that lets us override this on our CI at release distribution build time
- Having a bootstrap flag to pass through to `install_base_packages` to override this

**Comment by phyy-nx** [comment]
Hi, unfortunately removing libjpeg or using a containerized infrastructure
are the two preferable ways to do this.  Otherwise, you have would have to
check if any other package (besides wxWidgets) finds libjpeg and links
against it.  Plus it's not just libjpeg, it's any package found by these
configure scripts.  Thus, build systems should be minimal environments.

If you really can't change your build system, then
using --with-libjpeg=builtin in install_base_packages for wxWidgets seems
fine, with the caveat that there may be more work ahead to find other
dependencies on your build machine that the configure scripts are
automatically adding.

Note, the cci vms are not exempt from this.  For example, Billy is telling
me we have for example a sound package being pulled in by gtk or wx that we
can't find a way to turn off.  The struggle continues :)

-Aaron

On Thu, Jun 14, 2018 at 8:01 AM, Nicholas Devenish <notifications@github.com

**Comment by ndevenish** [comment]
So I've looked at the actual library dependencies (with `ldd`/`otool`) and it seems it's only the `libwx.*` libraries that end up linking to libjpeg in our builds - which is good as anything else would also be linking the wrong one.

Since it appears your builds already use the builtin, so this shouldn't affect your release process, any objections to adding this flag now?

**Comment by phyy-nx** [comment]
Nope!  No objections here.

-Aaron

On Wed, Jun 20, 2018 at 4:11 AM, Nicholas Devenish <notifications@github.com
