### ISSUE TITLE
viewer/boost_tst.py still required?

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#524]
The file https://github.com/dials/dials/blob/master/viewer/boost_tst.py does not seem to be imported from anywhere, is not included in ```run_tests.py```, so is not run as a test, and contains commented out code. Is this file still required or can it be removed?

**Comment by ndevenish** [comment]
A glance over history seems to imply it's a "scratch" script, rather than a "test something" script. The code it references, https://github.com/dials/dials/blob/821c12ae9c7f893b51e7dfd1cfd109f183eb7b04/viewer/rgb_2D.h#L35, seems to have been commented out in 2015, so that looks like it can along with it.
