### ISSUE TITLE
broken search_beam_position

### ISSUE THREAD

**Issue by ndevenish** [dials/dials#628]
Trying to work with some badly written data, search_beam_position failed to get solutions on the full set so restricted things to 2.5Å. Reciprocal lattice looks clean, apart from the issue that I'm trying to solve:
![image](https://user-images.githubusercontent.com/529963/46767795-fd0b1200-ccdd-11e8-8048-a4ae07fbc21d.png)

```
$ cd /dls/science/users/mep23677/pe/badsamples/beamc
$ dials.search_beam_position modified_datablock.json strong_inner.pickle
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  datablock = modified_datablock.json
  reflections = strong_inner.pickle
}

Running DPS using 8937 reflections
Found 7 solutions with max unit cell 41.22 Angstroms.
Traceback (most recent call last):
  File "/dls/science/users/mep23677/dist/build/../modules/dials/command_line/search_beam_position.py", line 513, in <module>
    run(sys.argv[1:])
  File "/dls/science/users/mep23677/dist/build/../modules/dials/command_line/search_beam_position.py", line 500, in run
    wide_search_binning=params.wide_search_binning)
  File "/dls/science/users/mep23677/dist/build/../modules/dials/command_line/search_beam_position.py", line 422, in discover_better_experimental_model
    new_detector = discoverer.optimize_origin_offset_local_scope()
  File "/dls/science/users/mep23677/dist/build/../modules/dials/command_line/search_beam_position.py", line 141, in optimize_origin_offset_local_scope
    potential_offsets[flex.min_index(potential_offsets.norms())])
RuntimeError: min_index() argument is an empty array
```

**Comment by rjgildea** [comment]
The issue is that all scores are zero, hence no scores remain after the selection at this line:
https://github.com/dials/dials/blob/master/command_line/search_beam_position.py#L138

When calculating the scores, kval is always much lower than kval_cutoff (by an order of magnitude. I'm not sure exactly what this signifies, but I presume it indicates that all the solutions are extremely weak, and either the true beam centre is outside of the search scope, or there is some other issue with the geometry that dials.search_beam_position can not resolve.
https://github.com/dials/dials/blob/master/command_line/search_beam_position.py#L270
