### ISSUE TITLE
Remove special cases for single panel detectors in image viewer

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#663]
The image viewer has special cases for single and multipanel detectors, however the time for this has long past.  This issue is here to track this problem, because fixing it requires several steps.

First, here's an example of why this matters.  Use dials.import on a single panel image, then run https://github.com/dials/dials/blob/single_panel_special_cases/util/image_viewer/slip_viewer/rotate_datablock.py which will rotate the detector by adjusting the origin, fast and slow vectors.  Use dials.image_viewer on the datablock and the viewer will not display a rotated image, even though the detector methods return the rotated coordinates correctly.  However, do this for a multipanel image, and the rotated image displays fine.  Current use case: Rayonix MX340 detector on its side at LCLS.  Since the data is rotated, polarization correction will be applied incorrectly.

Note, this isn't limited to datablocks.  A rotated full cbf exhibits the same issue.  However, check out the single_panel_special_cases branch and the images, either from a datablock or a rotated cbf, will display correctly.

Steps to fix:

1. The image viewer is currently duplicated in dials/util/image_viewer/slip_viewer because of wxPython 4 work.  However, I can't fix this issue until this duplication is resolved, as I want the fix in the cctbx copy of the code, but I also need to use dials.image_viewer.  Can we fold @ndevenish's changes back into rstbx and remove the duplicated code?
2. Commit 517d7af5b87bdfcd8340a5b894153c340146e81b in the single_panel_special_cases branch identifies where the special cases are.  In some of these the special case can be dropped, but in other cases the work around for multi-panel data is hacked in and should be resolved.
3. With this work, get_flex_image can be deprecated as get_flex_image_multipanel will be used exclusively

**Comment by graeme-winter** [comment]
@phyy-nx some thoughts

- right now we have a growing list of requirements for the dials image viewer including improving the performance, summing images (https://github.com/dials/dials/issues/660) and a "play" button (https://github.com/dials/dials/issues/661) - with the arrival of new Eiger detectors at Diamond there is a very close focus here on these tools
- recent changes pulled across from dials to cctbx (https://github.com/cctbx/cctbx_project/pull/198; https://github.com/cctbx/cctbx_project/pull/252) have included unwanted syntax changes which could well occur here
-  have already highlighted to @nksauter the change sets which I think cover the wxPython4 porting in https://github.com/cctbx/cctbx_project/issues/240 - copied below for convenience

Conclusion: I am not keen that we (Diamond staff) make the changes in the rstbx implementation of the image viewer for the wxPython4 code as usually our contributions include one or more unwelcome changes. I am also concerned that we could break something we are unable to test, which could affect one of your upcoming beam times. I am also not keen that we merge the two code bases as this will necessarily limit our developments to support user requirements highlighted above. 

Re: "Rayonix MX340 detector on its side at LCLS. Since the data is rotated, polarization correction will be applied incorrectly." - provided that the geometry is correctly assigned there should be no mathematical misunderstanding of the data - only the presentation in the image viewer is affected. We have a few detectors "on their side" here at Diamond and this works fine (you can check this with the dials geometry viewer)

https://github.com/dials/dials/commit/763925e668fd46154e61927a10bb84e0d9eeee5b
https://github.com/dials/dials/commit/a0374ab41df87802827500c50b5d733541da3ecd
https://github.com/dials/dials/commit/03072696eaeec99f7b7985704f661f2a62b9d43d
https://github.com/dials/dials/commit/7cbc4394e8cae5dc679e939e7b32428957ae38e3

**Comment by dagewa** [comment]
I hit this recently too - expected to see a large rotation in the image, but didn't. Aaron's analysis makes sense. Previously I have seen this on multi-panel detector images, but this was single panel.

**Comment by phyy-nx** [comment]
This is still broken and still an issue.  Happy to leave it self-assigned to me.  Might be able to fix it this spring.
