### ISSUE TITLE
Discussion on not storing shoeboxes from scaling onwards

### ISSUE THREAD

**Issue by jbeilstenedmands** [dials/dials#687]
I'm looking into improving the memory usage in scaling; one obvious problem is just that the reflection tables are pretty big by the time we get to scaling - just looking at typical refined.pickle and integrated.pickle files, you can see that the integrated files can typically be ~ 3x the size and it seems that almost half of the memory in an integrated.pickle is in the shoeboxes. 

If I were to delete the shoeboxes at the start of scaling and not carry them forward, it would be particularly helpful for memory management (alongside further improvements to the scaling code).
The only consequence I can think of is that this would mean this information is not available for the image viewer on a scaled.pickle (e.g for DUI), or for dials.report (but the shoeboxes aren't used here at the moment I think?). @jmp1985 do you know of any other cases where we might want the shoeboxes?

Any objections to me not taking the shoeboxes forward past scaling?
Of course these would still be available in the integrated.pickle file.

**Comment by graeme-winter** [comment]
Great idea! We can look at the integration results if they are needed - only need centroid position post scaling

**Comment by rjgildea** [comment]
You could make it an option e.g. delete_shoeboxes (default=True), then if someone *really* wants to keep them through scaling they can?

**Comment by jbeilstenedmands** [comment]
Yes I guess I might as well make it an option.

**Comment by dagewa** [comment]
The option sounds good. One thing I do in refinement that might also be helpful is to do all work on a copy of the reflection table that has everything non-essential for refinement deleted from it. At the end, the refined results are used to update the original reflection table. This appears helpful for speed with things like flex selections, though I do keep the original indexed reflections in memory (it would have been possible to read it back off from disk instead rather than keeping the copy around though).

**Comment by jbeilstenedmands** [comment]
@dagewa  thanks for the suggestion, I have considered doing something similar although I thought it would be a bit more involved but good to know that you found that this kind of thing helps - I will probably investigate this one when I have picked the lower hanging fruit, and the shoeboxes would be an easy big win for me :)
