### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by stranskj** [dials/dials#701]
I have a dataset, where dials.integrate consumes huge amount of memory, up to the level, where the PC is unusable, even when running with lower priority.
The data are pretty standard Pilatus 6M, 3600 frames. With other datasets, there was no issue. "Top" says, that 8.4GB is used per thread. The problems start, when "Integrating reflections" is running.
With nproc=1, the top memory consumption was 14.4GB.

Tested on the latest release 1.12.4, CentOS 7, i7-7700K, 32GB RAM, data are stored on cifs.

**Comment by jmp1985** [comment]
Hi @stranskj 

In order to try and diagnose the problem, could you post the dials.integrate.log file here or send to dials-support@lists.sourceforge.net?

James

**Comment by stranskj** [comment]
Hi @jmp1985,
here it is. This is complete log, which I got by running single threaded. When multithreaded, it stops around line 7961.
I can see, that there are some memory limits set later, it seems, that it is just allocated for each thread...
Jan
[dials.integrate.log](https://github.com/dials/dials/files/2813479/dials.integrate.log)

**Comment by jmp1985** [comment]
Hi @stranskj 

Thanks for sending the log file. I've had a look in the file and I can see that the mosaicity is very high:

 sigma m: 1.243098 degrees

This is usually the case if there is something wrong with the refinement. I suspect that if you look in the dials.refine.log file at the bottom you will see large RMSDs indicating that the predictions don't fit the observed positions. (could you attach this file too so that I can confirm this?) In this case, the mosaicity sometimes expands to compensate for the poorly determined spot positions and this results in large shoeboxes which take up too much memory. However, I should probably give more information in the log file rather than just allowing the program to use all the system memory!

**Comment by stranskj** [comment]
This might be the case, there is huge rmsd in Z:
`RMSDs by experiment:
--------------------------------------------
| Exp | Nref  | RMSD_X | RMSD_Y | RMSD_Z   |
| id  |       | (px)   | (px)   | (images) |
--------------------------------------------
| 0   | 54780 | 2.0596 | 2.8841 | 5.6599   |
--------------------------------------------
`
This is a troublesome dataset :-)

**Comment by jmp1985** [comment]
Ahh yes! That will be the problem! Also the RMSD for X and Y are also not good so even if it integrated you probably would not get great results!

I would suggest having a look at the indexing. I.e. what percentage of spots were indexed. Did you get the correct unit cell and space group etc? It might be worth posting all the log files on here!

**Comment by stranskj** [comment]
I definitely need to dive more into the processing, I didn't want to spam it here by data processing guidance :-) I just aimed to report the memory issue, because it can easily scare of less-PC-used users. That is good enough job for command line :-)

But thanks for tips anyway.

**Comment by dagewa** [comment]
Memory consumption in dials.integrate is still an issue, but this specific case seems to be due to poor experimental models.
