### ISSUE TITLE
dials.index real_space_grid_search not indexing all reflections it should

### ISSUE THREAD

**Issue by dagewa** [dials/dials#707]
The attached test case, [example.zip](https://github.com/dials/dials/files/2861077/example.zip), comes from a simulated still image that I am able to index using the `real_space_grid_search` method. I am using this command:

```console
dials.index stills.indexer=sweeps datablock.json strong.pickle unit_cell=78.840,78.840,38.290,90.000,90.000,90.000 space_group=P43212 method=real_space_grid_search
```

which indexes most, but not all, reflections:
```console
------------------------------------
| Imageset | #indexed | #unindexed |
------------------------------------
| 0        | 157      | 60         |
------------------------------------
```
None of the found reflections are noise (the image is simulated), so it should be possible to index every reflection. In the reciprocal lattice viewer the unindexed reflections form a band at one side:

![band](https://user-images.githubusercontent.com/11502083/52725152-88f0bb80-2fa8-11e9-8f40-6feb5b4068f1.png)

I can immediately index all the reflections by passing the output of the first job back into `dials.index`:

```console
dials.index experiments.json strong.pickle
...
------------------------------------
| Imageset | #indexed | #unindexed |
------------------------------------
| 0        | 217      | 0          |
------------------------------------
```
I'm trying to work out why I don't get this result the first time through.

**Comment by biochem-fan** [comment]
Hi David,

Does this happens with `fft1d` and `fft3d` as well? What happens if you fake the input as non-still?
I also have an impression that our still indexer rejects too much.
(see also https://github.com/dials/dials/issues/424, but probably the cause is different)

**Comment by dagewa** [comment]
Hi Takanori, thanks for your suggestions. Neither `fft1d` nor `fft3d` will index this image if I simply change the `indexing.method` in the command above. Other relevant information is that the image is from electron diffraction geometry, so the Ewald sphere is almost flat.

**Comment by dagewa** [comment]
In this case, switching off outlier rejection gives the same result, i.e. 157 indexed, 60 unindexed.

**Comment by dagewa** [comment]
Picking an X-ray rotation test case instead shows that `real_space_grid_search` _does_ do refinement in multiple macrocycles. So the fact I am getting just one macrocycle here seems to be either due to the electron diffraction geometry, or using a still.

**Comment by biochem-fan** [comment]
Yes, that is set in `stills_indexer.py` if I remember correctly.

**Comment by dagewa** [comment]
I see... I thought I was working around that with `stills.indexer=sweeps`, but maybe not. I will check. Thanks!

**Comment by biochem-fan** [comment]
https://github.com/dials/dials/blob/master/algorithms/indexing/stills_indexer.py#L116

**Comment by dagewa** [comment]
It turns out it happens here:
https://github.com/dials/dials/blob/96c97065f39fde38ca824d1c36aa95713b9c0d6c/algorithms/indexing/indexer.py#L489-L493
so even though I am getting an `indexer_real_space_grid_search` not a `stills_indexer_real_space_grid_search` the number of macrocycles has already been determined. If I set `n_macro_cycles=2` on my command then all 217 spots are indexed straight off.

So my question becomes, why is `n_macro_cycles = 1` considered an advantage for stills when, in this case at least, it gives a worse result? Looks like this dates back to #77. @phyy-nx I wonder if you could explain the reason for this default? Thanks.

**Comment by phyy-nx** [comment]
In this use case you are using the sweeps indexer on a still (stills.indexer=sweeps) which isn't something I've done a lot of.  In this case, a stills-specific default is used.  To be fair, the use case of using the sweeps indexer on a still isn't well delineated.  As an aside, doing it this way will also mean you don't get any mosaic estimates.

The reason for setting the default number of macrocycles to 1 is that the stills indexer doesn't implement macrocycles.  The thought at the time was that there generally aren't enough reflections on one image.  We'd need all the reflections we had to get indexing to work at all, so no low resolution limits are used during refinement.

I was curious how the stills indexer performs.  I couldn't index the example without adding a new flag:

`dials.index datablock.json strong.pickle unit_cell=78.840,78.840,38.290,90.000,90.000,90.000 space_group=P43212 stills.indexer=stills  refine_candidates_with_known_symmetry=True indexing.method=real_space_grid_search`

I got 201 reflections indexed out of 217.

refine_candidates_with_known_symmetry is a bit of a rabbit hole.  I've long suspected we should make it the default but haven't had a chance to investigate it more thoroughly.  I added it in #422 but reverted it in 9186af73254aad5ddca171ae6a5e93bee741318a.

**Comment by phyy-nx** [comment]
We cut this section from Brewster 2018 because of space reasons.  Here's a complete description of what the stills indexer does:

5.6.1	Indexing individual stills
We have implemented the following protocol for indexing still images in DIALS.  After a set of strong reflections are discovered:

1.	One or more candidate sets of lattices vectors are determined using fft1d or real space grid search as described in section 3.1.
2.	The best set of lattice vectors is determined with this procedure: for each candidate orientation matrix:
2.1.	Identify outliers by fitting the difference between observed and predicted X and Y positions of each reflection to a Rayleigh distribution, as described in (Sauter & Poon 2010).
2.2.	Refine the experimental models.  By default, the beam direction and wavelength as well as the detector position and tilt are fixed, so only the crystal model, including the cell parameters and crystal orientation, are refined.  Reflection positions are predicted using a procedure previously described, where reciprocal lattice points are rotated onto the Ewald sphere before they are used to compute the diffracted ray direction (Sauter et al. 2014).  Reflections are determined to be in the diffraction condition if their ΔΨ value (rotational offset off of the Ewald sphere) is less than 0.0015 radians (~0.1°).
2.3.	Identify outliers again using the refined models.
2.4.	Compute the mosaic domain size and mosaic block rotation angle for this crystal using the indexed reflections and a maximum likelihood target function that maximizes the probability of observing these reflections given a set of mosaic parameters (Nave 2014, Sauter et al. 2014).  This process also determines a set of outliers not predicted to be in the diffraction condition given the mosaic estimates.
2.5.	Refine again, using the estimated mosaic parameters to predict which reflections are in the diffraction condition.
2.6.	Re-compute the mosaic parameters using the refined experimental models.
2.7.	Stop if the root mean squared deviation (RMSD) of the differences between observed and predicted positions is greater than a certain cutoff (currently 1.5 mm), or if the Ewald proximal volume (defined below) is above 0.0015 reciprocal cubic Å.
2.8.	Choose the set of candidate basis vectors that predict reflections with the lowest positional RMSD of the observed-predicted residuals.
3.	Perform one final round of refinement using the best set of outliers and the best set of mosaic parameters.

**Comment by dagewa** [comment]
Hi Aaron, thanks for all the details. I found I needed `stills.indexer=stills` here to get anywhere, but I didn't know about `refine_candidates_with_known_symmetry=True`. I see the point about not having macrocycles for stills, but I wonder if here it is just the side effect of re-indexing after the first round of refinement that is helping out? Does the stills indexer attempt to index all reflections once it has refined what it thinks is the best model?

**Comment by phyy-nx** [comment]
It does reindex the reflections right before step 3.  So possibly!

**Comment by rjgildea** [comment]
With the changes in https://github.com/dials/dials/pull/708 dials.index now successfully indexes all reflections:

```
$ dials.index stills.indexer=sweeps datablock.json strong.pickle unit_cell=78.840,78.840,38.290,90.000,90.000,90.000 space_group=P43212 method=real_space_grid_search

...

################################################################################
Starting refinement (macro-cycle 3)
################################################################################

Detecting centroid outliers using the SauterPoon algorithm

Refinement steps:
-----------------------------------------------------
| Step | Nref | RMSD_X   | RMSD_Y   | RMSD_DeltaPsi |
|      |      | (mm)     | (mm)     | (deg)         |
-----------------------------------------------------
| 0    | 217  | 0.011954 | 0.012273 | 0.14266       |
| 1    | 217  | 0.011954 | 0.012273 | 0.14266       |
-----------------------------------------------------
RMSD no longer decreasing

RMSDs by experiment:
--------------------------------------------------
| Exp | Nref | RMSD_X  | RMSD_Y  | RMSD_DeltaPsi |
| id  |      | (px)    | (px)    | (deg)         |
--------------------------------------------------
| 0   | 217  | 0.21734 | 0.22315 | 0.14266       |
--------------------------------------------------

Refined crystal models:
model 1 (217 reflections):
Crystal:
    Unit cell: (78.847(14), 78.847(14), 38.285(6), 90.0, 90.0, 90.0)
    Space group: P 43 21 2
    U matrix:  {{-0.5313,  0.6305,  0.5659},
                { 0.2976, -0.4865,  0.8214},
                { 0.7932,  0.6048,  0.0708}}
    B matrix:  {{ 0.0127,  0.0000,  0.0000},
                {-0.0000,  0.0127,  0.0000},
                {-0.0000,  0.0000,  0.0261}}
    A = UB:    {{-0.0067,  0.0080,  0.0148},
                { 0.0038, -0.0062,  0.0215},
                { 0.0101,  0.0077,  0.0019}}

------------------------------------
| Imageset | #indexed | #unindexed |
------------------------------------
| 0        | 217      | 0          |
------------------------------------
Target d_min_final reached: finished with refinement
Saving refined experiments to experiments.json
Saving refined reflections to indexed.pickle
```

**Comment by dagewa** [comment]
closing this, now the test command is fixed and the issue is understood
