### ISSUE TITLE
DIALS 2 pre-commits

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#715]
* [ ] which pre-commits do we want
  * [ ] @ndevenish: a modified flake8 one (everything but stuff covered by black)
  * [x] @anthchirp: make an 'optional-black' hook
  * [ ] check-ast (Python 2 syntax)
* [ ] add pre-commit to list of dependencies
* [ ] automatically set up pre-commits for checked out code repositories dials & xia2 (or rather "if pre-commit module present and pre-commit files present in repo")

**Comment by Anthchirp** [comment]
done a quick test.

pre-commits need specifying
```language_version: libtbx.python```

pre-commit also has an undeclared dependency on newer version of pip (default 9.0.3 does not work, 10 probably fine, 18.1 is fine, current version is 19.0.3)
This would also be fixed by including Python 2.7.16 (has pip 18.1).
The 2.7.16rc1 is 10 days old, so I suspect 2.7.16 will be released before DIALS 2.

With both in place it will mostly work.

Not convinced we should install the pre-commit hook script by default. I think it would be better to make our own hook script that looks for the presence of libtbx.python and only then runs pre-commit. To be discussed I guess.

**Comment by Anthchirp** [comment]
Do we want any other pre-commit hooks?

**Comment by ndevenish** [comment]
I wonder if it might be worth just starting with a minimal flake8 for things that find_clutter does e.g.
```
flake8 --select=W291,W292,W293,F401
```
- **W291**: Trailing whitespace
- **W292**: no newline at end of file
- **W293**: Blank line contains whitespace
- **F401**: Module imported but unused

I know black covers the first three but since we're having black in a way that isn't guaranteed to run at least we'll have an extra layer. The F401 code is a little more robust that libtbx so picks up some more, and needs `# noqa` (general) or `# noqa: F401` (code-specific) to disable (you can turn off a code for specific lines or for the whole file).

There also appears to be a [plugin](https://pypi.org/project/flake8-future-import/) that adds warnings for missing `__future__` includes but I wonder if this is worth it because of py3 timelines (see ast3 discussion).

**Comment by Anthchirp** [comment]
https://github.com/asottile/reorder_python_imports is probably useful. Will test this during the blackening stage.
