### ISSUE TITLE
Opening files in image_viewer and reciprocal_lattice_viewer using GUI

### ISSUE THREAD

**Issue by benjaminhwilliams** [dials/dials#727]
A recent suggestion from users on I19.

Launching image_viewer and reciprocal_lattice_viewer requires passing an experiment list (legacy: datablock) and, for r_l_v, a reflection table as minimal arguments.  In i_v there is a menu option to open individual images in a GUI file explorer.  User suggests that it would be useful to be able to browse experiment lists and reflection tables in this way.  It would then be possible to open the i_v and/or r_l_v without arguments and browse, or with arguments in the familiar way.

**Comment by benjaminhwilliams** [comment]
Being a suggestion related to UI, I realise this may stray into an existential debate about DUI...

**Comment by dagewa** [comment]
@graeme-winter looked into this in #700 and concluded it was difficult. However, I can see it would be very useful. Having sat with local contacts while collecting data and seeing them manually opening `dials.image_viewer` after copying paths from ISPyB to view EIGER images, I think Diamond needs this functionality and it might be worth however vicious the refactor turns out to be.

**Comment by benjaminhwilliams** [comment]
Ah, thanks for the pointer to #700, I knew what I was asking rang a bell.  OK, I'll leave this to longer-term planning and discussion.

Duplicates #700.
