### ISSUE TITLE
stills_process test failing on Mac

### ISSUE THREAD

**Issue by Anthchirp** [dials/dials#736]
The test test_stills_process.test_sacla_h5[False] is failing on Mac at
https://github.com/dials/dials/blob/9e7ea566f4cbd668b7c09e6a82568d54d84bf4b6/test/command_line/test_stills_process.py#L128-L138
with
```
E           AssertionError: ('idx-run266702-0-subset_00003_integrated.pickle', 472)
E           assert 472 in [475, 476, 477, 478, 479, 480, ...]
E            +  where 472 = len(<dials_array_family_flex_ext.reflection_table object at 0x121ef9e68>)

../../../../build_dials/modules/dials/test/command_line/test_stills_process.py:138: AssertionError
```

**Comment by phyy-nx** [comment]
Investigating.  I've reproduced it.  According to buildbot it broke between Mar 13 and 14.  Bisecting.

**Comment by rjgildea** [comment]
Likely candidate? https://github.com/dials/dials/commit/85fa264edafb655699cf30bbd536c47416c9a1ef

Does this affect stills process?

**Comment by phyy-nx** [comment]
Yah that's it.  The shoe boxes are a lot bigger so some of the predictions seem to be thrown out.  Can someone explain #731 to me?  What is actually being fixed?

**Comment by phyy-nx** [comment]
Before:
![image](https://user-images.githubusercontent.com/13471434/54942847-3383c480-4eed-11e9-8634-f73b80ca1835.png)

After:
![image](https://user-images.githubusercontent.com/13471434/54942864-3bdbff80-4eed-11e9-9622-de4e2ae0c6bf.png)

This is a huge difference!

**Comment by phyy-nx** [comment]
Reproduce:
Before: git checkout 1f15270a7064bd0f8141dc20ce0ffc5270b0d4ca
After: git checkout 85fa264edafb655699cf30bbd536c47416c9a1ef

**Comment by graeme-winter** [comment]
@phyy-nx - this change made a huge difference to the quality of processed data for more mediocre samples, and literally no difference for nice rotation data - am surprised it's so different here.

The logic is that the profile parameters should be w.r.t. the predicted position, since that is the centroid used for integration, not the observed spot size w.r.t. the centroid. 

I can however see that this could be different for still shots. For rotation data it has given either no change or an improvement across the board... 

To be sure, is it the case that integration is worse, or the results have just changed so the test now fails?

**Comment by graeme-winter** [comment]
Close button next to comment != helpful 🙄

**Comment by phyy-nx** [comment]
> To be sure, is it the case that integration is worse, or the results have just changed so the test now fails?

Dunno!  I'd have to re-process and re-merge a big xfel dataset and find some metrics.  Not a trivial task.

Again, some reflections are now gone near the edges of the panels, likely because the masks are now hitting the 1 pixel border which is flagged as bad (IIRC for SACLA data).  Whether A) the integration masks are better with this change and B) even if they are, if that compensates for the missing data, I don't know.

**Comment by phyy-nx** [comment]
Hm, maybe a few more details?  I'm not sure I understand what you are saying.  Are you saying that instead of using the spotfinder foreground pixels for profile building, you are using a new set of pixels near the spot prediction?  How is that set of pixels determined?

Regardless, I think we need a phil option to turn on and off this new behavior.  Without that phil option we can't really study the effects of the new code.  For example, how does this work on a Rayonix CCD image (big point spread function) with a large unit cell? The old style profiles were fine even if the spot separation was pretty tight.  These larger ones make me nervous.

Who could do this phil option?  I'd prefer the original authors of #731 to do it :)

As an aside, sorry the stills process test wasn't robust enough to catch this.  The fact it passes on linux and not mac is disquieting.  It needs to do more than count the number of integrated reflections, I fear.

**Comment by biochem-fan** [comment]
This is very interesting. In my experience, DIALS's integration masks for MPCCD tend to be too small (see #426). CrystFEL uses circles of a user-provided radius (not diameter), where 3-4 px for integration and 5-7 px for background usually give the best result. So this larger shoebox might improve the result, but we need testing. I support Aaron's suggestion. An option to specify the radius as in CrystFEL would be also very useful.

**Comment by graeme-winter** [comment]
Tricky thing with adding a PHIL parameter (which I agree is a good idea) is that it is probably many many layers down the call stack. Will have a look-see. 

@phyy-nx big round spots should be fine. This mostly improves cases with PADs where you have "fine structure" in the spot...

Detail:

- not discovering new pixels for profile parameter determination
- comparing the existing distribution of pixel density to the predicted centroid not observed centre of mass
- since the measurement box centred on prediction not centroid, makes more sense? discuss

**Comment by phyy-nx** [comment]
Good, happy you agree about the phil parameter.   Stating it a bit more clearly, the old algorithm was being used as a baseline for other projects in development so we have to keep it around.  Happy to learn about the new one, but we gotta keep the old one.

If it were just a little change I'd be less vocal :)

**Comment by phyy-nx** [comment]
> since the measurement box centred on prediction not centroid, makes more sense? discuss

Maybe?  But using the observed centroid for building the profile takes into account errors in the model that lead to mispredicted spot locations.

You see a big improvement.  Does that improvement come just from the bigger masks?

**Comment by graeme-winter** [comment]
Nope - in some cases the mask sizes are identical - I think it is generally more right sized masks why it is helping.

**Comment by graeme-winter** [comment]
Will be ```gaussian_rs.centroid_definition``` enum of 

- centre of mass => com
- s1 vector (prediction) => s1

**Comment by phyy-nx** [comment]
👍

**Comment by graeme-winter** [comment]
testing code changes now - @phyy-nx where to set the default for your code?

**Comment by phyy-nx** [comment]
https://github.com/dials/dials/blob/master/command_line/stills_process.py#L158-L188

**Comment by graeme-winter** [comment]
Fixes incoming

**Comment by graeme-winter** [comment]
verified with 

```
pytest -s /Users/graeme/svn/cctbx/modules/dials/test/command_line/test_stills_process.py 
```

before & after

**Comment by phyy-nx** [comment]
Confirmed.  Thanks.  For now, the default in stills process is the new behavior (s1) but the test tests the old behavior (com).  We'll watch and see what effect the new behavior has on xfel data.  If things do show an improvement I'll update the test.
