### ISSUE TITLE
dials.combine_experiments reference_from_experiment: more useful error messages

### ISSUE THREAD

**Issue by rjgildea** [dials/dials#788]
When using the reference_from_experiments the error messages in event of failed comparison are not particularly useful, other than "something is wrong with the beam comparison":
```
$ dials.combine_experiments indexed* reference_from_experiment.detector=0 reference_from_experiment.beam=0 
Sorry: Beam didn't match reference within required tolerance for experiment 1 in indexed_experiments.json
       Adjust tolerances or set compare_models=False to ignore differences.
```
It would be more useful if it could specify which beam attribute(s) was the cause of comparison failure, and how much outside the tolerance the attribute was.

**Comment by dagewa** [comment]
This is slightly tricky because the comparisons rely on `is_similar_to` functions, which are C++ and strictly bool
https://github.com/dials/dxtbx/blob/20bd1171c2e4d82b99162151854f43d5a211cf6b/datablock.py#L1203-L1212
I suppose one option would be for the dxtbx models to have `diff` functions that follow a similar logic as `is_similar_to` but return a string indicating the difference(s) between the models

**Comment by rjgildea** [comment]
Like this?
https://github.com/dials/dxtbx/blob/20bd1171c2e4d82b99162151854f43d5a211cf6b/datablock.py#L1276-L1314
