### ISSUE TITLE
dispersion_extended spot finding breaks xia2 processing large data sets

### ISSUE THREAD

**Issue by graeme-winter** [dials/dials#816]
xia2 used to work on 

```
DIRECTORY /dls/i03/data/2019/cm23003-2/gw/20190424/firehose-collect/protk_1_13
IMAGE protk_1_13_3_master.h5
```

now (with this as the default) pulls a -9

**Comment by graeme-winter** [comment]
New sigma values were:

```
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
 sigma b: 0.045853 degrees
 sigma m: 0.225209 degrees
```

old were

```
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
 sigma b: 0.023450 degrees
 sigma m: 0.140878 degrees
```

seems to be enough to push over the edge.

**Comment by rjgildea** [comment]
Look at this example, I think it was by happy accident that the full 28000 image dataset worked before. Re-running the processing on the first 3600 images, I get an integration memory failure for both dispersion and dispersion_extended algorithms.

The calculated sigma values are not significantly different for either spot-finding algorithm (and both larger than the values quoted above for the full dataset).
```
$ grep sigma dispersion*_3600/DEFAULT/NATIVE/SWEEP1/integrate/13_dials.integrate_INTEGRATE.log
dispersion_3600/DEFAULT/NATIVE/SWEEP1/integrate/13_dials.integrate_INTEGRATE.log:    sigma divergence: 0
dispersion_3600/DEFAULT/NATIVE/SWEEP1/integrate/13_dials.integrate_INTEGRATE.log: sigma b: 0.040348 degrees
dispersion_3600/DEFAULT/NATIVE/SWEEP1/integrate/13_dials.integrate_INTEGRATE.log: sigma m: 0.205931 degrees
dispersion_extended_3600/DEFAULT/NATIVE/SWEEP1/integrate/13_dials.integrate_INTEGRATE.log:    sigma divergence: 0
dispersion_extended_3600/DEFAULT/NATIVE/SWEEP1/integrate/13_dials.integrate_INTEGRATE.log: sigma b: 0.045607 degrees
dispersion_extended_3600/DEFAULT/NATIVE/SWEEP1/integrate/13_dials.integrate_INTEGRATE.log: sigma m: 0.215494 degrees
```
Comparing the spotfinding output, the new algorithm actually finds more strong pixels, despite finding fewer strong spots. I think this is because the new algorithm is better at finding contiguous regions of strong pixels when the spots are large, whereas the old algorithm finds disconnected regions of strong pixels that should be part of the same physical spot.

algorithm=dispersion:
```
Found 4116 strong pixels on image 1
Found 4041 strong pixels on image 2
Found 4083 strong pixels on image 3
Found 4090 strong pixels on image 4
Found 4108 strong pixels on image 5
Found 4176 strong pixels on image 6
Found 4100 strong pixels on image 7
Found 4164 strong pixels on image 8
Found 4189 strong pixels on image 9
Found 4169 strong pixels on image 10
...
Extracted 3063952 spots
Removed 2629888 spots with size < 3 pixels
Removed 547 spots with size > 1000 pixels
Calculated 433517 spot centroids
Calculated 433517 spot intensities
Filtered 379080 of 433517 spots by peak-centroid distance
```

algorithm=dispersion_extended:
```
Found 9437 strong pixels on image 1
Found 9513 strong pixels on image 2
Found 9519 strong pixels on image 3
Found 9629 strong pixels on image 4
Found 10022 strong pixels on image 5
Found 9832 strong pixels on image 6
Found 9661 strong pixels on image 7
Found 9642 strong pixels on image 8
Found 9560 strong pixels on image 9
Found 9355 strong pixels on image 10
...
Extracted 734234 spots
Removed 456776 spots with size < 3 pixels
Removed 7209 spots with size > 1000 pixels
Calculated 270249 spot centroids
Calculated 270249 spot intensities
Filtered 217417 of 270249 spots by peak-centroid distance
```
Also note that a significantly higher proportion of spots are removed by the max spot size and peak-centroid filters, suggesting that these default values might be over-conservative with the new algorithm.

The new algorithm seems to do a better job of finding the strong pixels than the old algorithm, leading to larger bounding box sizes, and presumably leading to larger (and more realistic?) estimates of sigma_m and sigma_b, which exacerbates memory issues in integration.

algorithm=dispersion:
![Screenshot from 2019-06-13 10-29-07](https://user-images.githubusercontent.com/2810624/59421245-2ed0fd00-8dc6-11e9-90f1-b56c6b7c6a40.png)

algorithm=dispersion_extended:
![Screenshot from 2019-06-13 10-29-35](https://user-images.githubusercontent.com/2810624/59421417-75265c00-8dc6-11e9-94d0-64d801e43e1d.png)

**Comment by rjgildea** [comment]
Results of processing the first 3600 images using nproc=4 (but reserving 20 cpus/memory) would suggest that the new spotfinding algorithm does indeed lead to better integrated data:
![cc_one_half](https://user-images.githubusercontent.com/2810624/59430267-bf650880-8dd9-11e9-9563-8bf28e18fcbd.png)
![i_over_sigma_mean](https://user-images.githubusercontent.com/2810624/59430274-c4c25300-8dd9-11e9-8064-732e226b940e.png)
![r_merge](https://user-images.githubusercontent.com/2810624/59430286-ca1f9d80-8dd9-11e9-9292-0dcc04f70597.png)
![r_pim](https://user-images.githubusercontent.com/2810624/59430291-cd1a8e00-8dd9-11e9-9b8b-6e02d3ec8c6e.png)
As far as I can tell, the reason these data previously processed was because the inferior spot-finding algorithm resulted in a sub-standard integration model.

**Comment by graeme-winter** [comment]
Thanks for the additional information on this one - will look at the behaviour with threaded integrator - just need to figure out passing options through xia2 to
- switch off shadows (because Python masking) 
- use threaded integrator
- use new spot finding

Will copy here once these done...

**Comment by rjgildea** [comment]
>     * switch off shadows (because Python masking)
dynamic_shadowing=False

>     * use new spot finding

```
cat > find_spots.phil << EOF
spotfinder.threshold.algorithm=$algorithm
EOF
xia2 dials.find_spots.phil_file=find_spots.phil ...
```

>     * use threaded integrator
```
cat > integrate.phil << EOF
integration.integrator=3d_threaded
EOF
xia2 dials.integrate.phil_file=integrate.phil ...
```

**Comment by graeme-winter** [comment]
testing

```
find.phil
spotfinder {
  threshold {
    algorithm = dispersion_extended
  }
}


integrate.phil
integration {
  integrator = 3d_threaded
}
```

+ 

```
module load dials/latest

PHIL=/dls/i03/data/2019/cm23003-3/processing/gw/big-set-benchmark

xia2 find_spots.phil=${PHIL}/find.phil \
integrate.phil_file=${PHIL}/integrate.phil \
dynamic_shadow=0 \
atom=S image=/dls/i03/data/2019/cm23003-2/gw/20190424/firehose-collect/protk_1_13/protk_1_13_1_master.h5
```

to give this all a good workout...

**Comment by graeme-winter** [comment]
Running in /dls/i03/data/2019/cm23003-3/processing/gw/big-set-benchmark/20190613
