### ISSUE TITLE
Mosaicity in dials.integrate.log

### ISSUE THREAD

**Issue by dagewa** [dials/dials#909]
More than once I have seen user requests along the lines of "where does dials.integrate report mosaicity?" Lines in the the log file like

```
Calculating E.S.D Beam Divergence.
Calculating E.S.D Reflecting Range.
 sigma b: 0.021848 degrees
 sigma m: 0.065720 degrees
```
are not very clear that `sigma m` relates to a "mosaicity" parameter. How might we change this output to be more obvious and useful to users?

**Comment by graeme-winter** [comment]
Completely understand your viewpoint

Two observations here:

 - reporting these at the _end_ of the log as well as calculation time would be helpful
 - explaining that this is mosaic spread and what it _means_ would also help

Any changes would need to be propagated to xia2 because log file scraping but that is trivial.

Further to this: I think a concrete histogram of the number of images the peak region is spread across would also be helpful i.e. showing how the Lorenz factor affects things.

**Comment by rjgildea** [comment]
xia2 _shouldn't_ be scraping the log file to get this information. It should get directly from reading the profile model attached to the experiment:

https://github.com/xia2/xia2/blob/f235b1992fe4b9b05687d1c7121a6bfdaa7ceefd/Modules/Integrater/DialsIntegrater.py#L404-L407

**Comment by graeme-winter** [comment]
@rjgildea  👍
