### ISSUE TITLE
Deleting scans/goniometers from stills

### ISSUE THREAD

**Issue by dagewa** [dials/dials#971]
2 reasons as to why the scan/gonio are deleted during indexing stills (these reasons may no longer apply).  1) There are assumptions in place in the stills indexer/integrator that lack of a scan/gonio is the definition of whether something is a still.  Deleting them early ensures everything downstream knows what is going on.  For example, it guarantees the stills integrator is used for a sweep with the oscillation angle set to zero, which should be treated as a still.  2) It ensures that any code that assumes a sweep will fail since the gonio/scans are None. This is more of a safety check.

If these reasons are no longer applicable, we can discuss not deleting the scan/gonio, as long as the stills indexer and integrator remain automatically triggered for oscillation=0.

_Originally posted by @phyy-nx in https://github.com/dials/dials/pull/970#issuecomment-543207099_

**Comment by dagewa** [comment]
At the moment, you might have an `ImageSequence` that you want to treat as stills. This has been done by setting `scan` and `goniometer` objects to `None`. The result can be serialised, but on loading again fails with
```
AssertionError: Can't create Sequence without goniometer
```
f3e80e9 works around this in indexing by coercing an `ImageSequence` to `ImageSet`.

Our ultimate aim is to allow stills experiments with goniometers and zero width scans to persist throughout processing (a zero width scan and goniometer is still useful if e.g. you have another still at a defined rotation from the first).

This is a place for discussion.

**Comment by ndevenish** [comment]
> There are assumptions in place in the stills indexer/integrator that lack of a scan/gonio is the definition of whether something is a still

We've had `is_still` on [experiment objects](https://github.com/cctbx/dxtbx/blob/b4ef6a89b1d9a813bc94dd57413aafc74fc1203d/model/experiment.h#L152-L154) for a while; I thought we went though to try and update everywhere looking for stills but looks like that didn't happen.

In any case, changing the code to having this decision in one place rather than scattered throughout the codebase can only be a good thing, and gives us a place to store experiment/varying information related to a still sequence.

>  as long as the stills indexer and integrator remain automatically triggered for oscillation=0.

Do we actually need this behaviour? As I understand it,
- processing still data outside of `stills_process` has _never_ worked for more than one image - and stills_process has control so can ensure that the correct index/integrator method is chosen
- it's confusing to have such different behaviour switched on something hidden like this; "method is the method except when `stills.indexer=sweeps`" is horribly confusing and seems reasonably unnecessary - why can't we have `method=stills` and get rid of `I_know_what_I_said_but_sometimes_really_use_this_one_instead=`
- `Auto` is essentially meaningless for users running `-ce`

Is there any compelling reason to keep the current switching behaviour?

**Comment by phyy-nx** [comment]
Generally on board.  The trick is to find all the places where lack of a gonio/scan is used as a signal.  It didn't take me more than a minute to find this example:
https://github.com/dials/dials/blob/master/algorithms/indexing/indexer.py#L325
I'm pretty sure there are more.

**Comment by rjgildea** [comment]
Here is a list of places in dials where we explicitly test that `goniometer is [not] None`:
```
$ find . -name "*.py" -type f | xargs grep -nr "gonio.* is .*None"
./util/reciprocal_lattice/__init__.py:61:        if self.experiments[0].goniometer is not None:
./util/export_sadabs.py:54:    assert experiment.goniometer is not None
./util/nexus/nx_mx.py:302:    if scan is None or goniometer is None:
./util/nexus/nx_mx.py:727:        if experiment.goniometer is not None:
./util/export_xds_ascii.py:97:    if experiment.goniometer is None:
./util/export_xds_ascii.py:169:    if experiment.goniometer is not None:
./util/export_mtz.py:157:        if experiment.goniometer is not None:
./util/image_viewer/spotfinder_frame.py:1524:                    still = scan is None or gonio is None
./algorithms/refinement/refiner.py:964:            if goniometer is None:
./algorithms/refinement/refiner.py:995:            if goniometer is None:
./algorithms/refinement/prediction/managed_predictors.py:172:                if exp.goniometer is None:
./algorithms/refinement/restraints/restraints_parameterisation.py:96:        if goniometer_parameterisations is None:
./algorithms/refinement/target.py:239:            if exp.goniometer is None:
./algorithms/refinement/parameterisation/scan_varying_prediction_parameters.py:135:        if goniometer_parameterisations is None:
./algorithms/refinement/parameterisation/scan_varying_prediction_parameters.py:234:        if param_set.gonio_param is not None:
./algorithms/refinement/parameterisation/parameter_report.py:37:        if goniometer_parameterisations is None:
./algorithms/refinement/parameterisation/configure.py:475:        if goniometer is None:
./algorithms/refinement/parameterisation/configure.py:709:        if goniometer is None:
./algorithms/refinement/parameterisation/prediction_parameters.py:68:        if goniometer_parameterisations is None:
./algorithms/indexing/indexer.py:325:            if self.experiments[0].goniometer is None:
./algorithms/indexing/indexer.py:335:            if expt.goniometer is not None and expt.goniometer.is_similar_to(
./algorithms/indexing/indexer.py:382:                    expt.goniometer is None
./algorithms/profile_model/gaussian_rs/__init__.py:55:    if goniometer is None or scan is None or scan.get_oscillation()[1] == 0:
./algorithms/profile_model/gaussian_rs/__init__.py:64:    if goniometer is None or scan is None or scan.get_oscillation()[1] == 0:
./algorithms/profile_model/gaussian_rs/__init__.py:73:    if goniometer is None or scan is None or scan.get_oscillation()[1] == 0:
./algorithms/profile_model/gaussian_rs/model.py:597:                or experiment.goniometer is None
./algorithms/profile_model/gaussian_rs/calculator.py:534:        if goniometer is None or scan is None or scan.get_oscillation()[1] == 0:
./array_family/flex.py:963:            if experiment.goniometer is not None:
./array_family/flex.py:1395:                if expt.goniometer is not None:
./command_line/show.py:248:        if expt.goniometer is not None:
./command_line/search_beam_position.py:363:    if goniometer is None:
./command_line/index.py:163:            expt.goniometer is not None
./command_line/geometry_viewer.py:68:        if self.imageset.get_goniometer() is not None:
./command_line/geometry_viewer.py:116:        if gonio_masker is None:
./command_line/geometry_viewer.py:488:        elif gonio is not None:
./command_line/geometry_viewer.py:641:    if gonio is not None and not isinstance(gonio, MultiAxisGoniometer):
./command_line/find_spots_server.py:151:            imageset.get_goniometer() is not None
./command_line/integrate.py:232:            if exp.goniometer is not None and exp.scan is not None:
./command_line/refine_bravais_settings.py:189:        if experiments[0].goniometer is None:
./command_line/dials_import.py:406:            assert (goniometer is None and g_i is None) or goniometer.is_similar_to(
./command_line/combine_experiments.py:420:        if ref_goniometer is not None:
./command_line/report.py:2339:            if expt.goniometer is not None:
./command_line/stereographic_projection.py:90:    if goniometer is not None:
```

**Comment by graeme-winter** [comment]
On topic of "For example, it guarantees the stills integrator is used for a sweep with the oscillation angle set to zero, which should be treated as a still." - 

I can see a world in the not-too-distant future where an ImageSequence with scans with 0 oscillation are treated by analogy with sweeps rather than as a collection of unrelated images. We need to start working on these with shared models for beam, detector etc. for the analysis work we need on Diamond beamlines, which may (in future) deviate from treatment of individual still shots from an X-FEL, where things really do vary on a shot-to-shot basis. 

The idea behind the ImageSweep -> ImageSequence relabel earlier this week was to begin the foundation work for this. 

I propose: ImageSets maintain the existing behaviour by _not having scans and goniometers_ whereas ImageSequence behaviour may be mutable in future. This distinction is made to prevent any risk of change to e.g. `dials.stills_process`.
