### ISSUE TITLE
Simple filenames broken

### ISSUE THREAD

**Issue by phyy-nx** [dials/dials#972]
Reported by a phenix user.  Steps to reproduce:

```
cd $dials_regression/image_examples/ALS_831
dials.image_viewer q315r_lyso_001.img # this works fine
cp q315r_lyso_001.img q315r_lyso1.img
dials.image_viewer q315r_lyso1.img
```

Result:
`Sorry: Could not determine filename template`

**Comment by nksauter** [comment]
Aaron,

Not to be argumentative, but renaming the file to have only a single
numerical digit after the file root "q315r_lyso", goes against decades of
tradition:  image filenames simply must have a sequence number like 001 or
0001 in order to place them in the context of a scan.  This was always the
case, for example, with programs like Labelit.  The error message reflects
this reality.

Since 2010 the experience with serial crystallography has modified the
expectation somewhat, but the newer expectations do not apply to the *.img
filename extension I would imagine.

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by phyy-nx** [comment]
Right, that makes sense.  The specific user had a file named TS1.mccd.  I'm not sure how this file was created.  I'm ok with the answer to the user being 'rename the file'.

**Comment by ndevenish** [comment]
If at all possible we should try to fix this, even if it doesn't make total sense to have such a file.

It's unreasonable to have something called `image_viewer` not read images because they are _named_ wrong.

**Comment by graeme-winter** [comment]
The current handling of templates is known to be somewhat broken - see also:

https://github.com/cctbx/cctbx_project/pull/236

from @alyubimov - I think the current behaviour of simply saying "no" could be easily adjusted to something which works but does not have to be _right_. As @nksauter points out no one would collect a data set like this but I have frequently had users email one frame to look at which they would rename to "myframe1.img" or something - I know to rename it before trying to import but it could be made to work. 

It does not matter if the template is wrong, only that the template works enough to allow the image to be read.
